/**
 * Useful routines for native workstation sessions.
 * Routine selection populates prompt drafts only; no auto-dispatch or scheduler.
 */
import type { WorkstationRoutine } from "@cadrane/contracts";

export type { WorkstationRoutine };

export const WORKSTATION_ROUTINES: readonly WorkstationRoutine[] = [
  {
    id: "research-brief",
    title: "Source-Grounded Research Brief",
    description:
      "Synthesize selected sources into an evidence-backed research brief with explicit citations, uncertainty flags, and review criteria.",
    icon: "research",
    sourceHint:
      "Select reference documents, interview transcripts, articles, or notes to ground this brief.",
    outputLabel: "Research Brief",
    prompt: [
      "You are preparing a rigorous, evidence-grounded research brief. Every assertion must be anchored in the selected sources.",
      "",
      "## Required Input Needs",
      "- Topic or research question: [State clearly what specific question this brief answers]",
      "- Grounding sources: [Ensure relevant notes, reports, transcripts, or reference documents are selected]",
      "",
      "## Evidence & Citation Expectations",
      "- Ground every factual statement directly in the provided sources.",
      "- Cite specific sources inline using the format [Source: <Name or Turn ID>].",
      "- If an assertion is an inference rather than a direct quote or factual statement, explicitly label it [Inference: <Rationale>].",
      "- Do not fabricate citations, extrapolate beyond source evidence, or rely on unstated external assumptions.",
      "",
      "## Output Structure",
      "Structure the brief into the following sections:",
      "1. Executive Summary: Core takeaway and synthesized conclusions in 2-3 concise paragraphs.",
      "2. Key Findings & Evidence: Detailed findings organized by theme, with inline source citations for each point.",
      "3. Comparative Matrix: Tabular summary comparing key dimensions, source viewpoints, or options.",
      "4. Contradictions & Gaps: Points where sources disagree or where evidence is silent.",
      "5. Strategic Implications: Practical consequences and recommendations for stakeholders.",
      "6. Limits & Uncertainty: Explicitly state data boundaries, sample limits, and unverified areas.",
      "",
      "## Acceptance & Sign-off Questions",
      "Before accepting this artifact, verify:",
      "- Can every factual claim be traced to a specific line or section in the selected sources?",
      "- Are inferences and speculations clearly distinguished from source-verified facts?",
      "- Are opposing viewpoints and data gaps acknowledged rather than smoothed over?"
    ].join("\n")
  },
  {
    id: "client-proposal",
    title: "Client Proposal",
    description:
      "Draft a persuasive, scoped commercial proposal grounded in client needs, deliverables, milestones, and risk boundaries.",
    icon: "write",
    sourceHint:
      "Select discovery meeting notes, RFPs, client correspondence, or project briefs.",
    outputLabel: "Client Proposal",
    prompt: [
      "You are preparing a professional, client-ready commercial proposal. Ground the narrative in client requirements and realistic operational boundaries.",
      "",
      "## Required Input Needs",
      "- Client background: [Client context, industry domain, and core stakeholders]",
      "- Stated business challenge: [Specific pain points or opportunities extracted from discovery sources]",
      "- Commercial & timeline constraints: [Target delivery dates, budget expectations, or staffing limits]",
      "",
      "## Evidence & Citation Expectations",
      "- Anchor the problem statement and client goals in direct statements from discovery notes using [Ref: <Document/Turn>].",
      "- Explicitly trace proposed solutions to stated client priorities.",
      "- Do not make commercial commitments or pricing guarantees that exceed the provided source context.",
      "",
      "## Output Structure",
      "Structure the proposal into the following sections:",
      "1. Executive Summary & Objective: High-level overview of the partnership and value proposition.",
      "2. Problem Statement & Desired Outcomes: Clear articulation of current state versus target future state.",
      "3. Proposed Solution & Scope of Work: Specific workstreams, methodologies, and architectural approaches.",
      "4. Deliverables & Milestone Schedule: Table of deliverables, target timelines, and completion criteria.",
      "5. Roles, Responsibilities & Dependencies: Client prerequisites, third-party access needs, and escalation paths.",
      "6. Commercial Terms & Resource Model: Staffing allocation, fee structure, and payment milestones.",
      "7. Out-of-Scope Exclusions & Boundary Conditions: Explicit list of work excluded from this engagement.",
      "8. Risk Management & Mitigations: Anticipated operational or technical risks with concrete mitigations.",
      "",
      "## Limits & Uncertainty",
      "- Highlight any unconfirmed scope items or dependencies requiring client validation before contract signing.",
      "- Call out pricing assumptions that depend on third-party licensing or infrastructure costs.",
      "",
      "## Acceptance & Sign-off Questions",
      "Before accepting this artifact, verify:",
      "- Does the scope clearly separate included deliverables from out-of-scope requests?",
      "- Are client dependencies and prerequisites realistic and agreed upon?",
      "- Are milestone acceptance criteria objective and testable by both parties?"
    ].join("\n")
  },
  {
    id: "engineering-review",
    title: "Engineering Change Review",
    description:
      "Evaluate an architectural change, pull request, or technical RFC against correctness, security, performance, and operational risk.",
    icon: "review",
    sourceHint:
      "Select git diffs, PR descriptions, RFC drafts, system design docs, or issue threads.",
    outputLabel: "Engineering Review",
    prompt: [
      "You are conducting a thorough, critical engineering change review. Evaluate technical soundness, systemic risk, and architectural alignment.",
      "",
      "## Required Input Needs",
      "- Change specification: [Pull request diff, RFC document, or architecture proposal]",
      "- System context: [Affected services, database schemas, API contracts, or protocols]",
      "- Operational requirements: [SLA targets, latency constraints, concurrency profiles]",
      "",
      "## Evidence & Citation Expectations",
      "- Reference exact filenames, line numbers, function signatures, or RFC sections using `file:line` or [RFC §X.Y].",
      "- Quote relevant code snippets or invariants when demonstrating potential regressions or race conditions.",
      "- Base security and performance critiques on verified runtime characteristics, not vague generalities.",
      "",
      "## Output Structure",
      "Structure the review into the following sections:",
      "1. Change Summary & Intent: Concise description of what the change does and why it was introduced.",
      "2. Architecture & Invariants Analysis: How this change affects core data structures, state machines, and system invariants.",
      "3. Correctness & Edge Cases: Analysis of boundary conditions, concurrency/race conditions, and error recovery.",
      "4. Security & Privacy Impact: Authentication/authorization boundaries, data leakage, injection surfaces, and permissions.",
      "5. Performance & Resource Footprint: Memory allocations, database query plans, connection pooling, and I/O bottlenecks.",
      "6. Compatibility & Migration Plan: Schema migrations, backward compatibility, rollback strategy, and feature flagging.",
      "7. Code Snippets & Remediation: Concrete diffs or code blocks demonstrating recommended fixes.",
      "8. Unresolved Questions & Missing Tests: Gaps in test coverage and behavioral unknowns under load.",
      "",
      "## Limits & Uncertainty",
      "- State which execution paths could not be fully verified from the static diff alone.",
      "- Note any unbenchmarked performance assumptions that require live profiling.",
      "",
      "## Acceptance & Sign-off Questions",
      "Before approving or merging this change, verify:",
      "- Is the rollback procedure safe, deterministic, and tested without data loss?",
      "- Are all modified public interfaces backward-compatible or versioned?",
      "- Does the automated test suite exercise failure modes and edge cases identified in this review?"
    ].join("\n")
  },
  {
    id: "implementation-plan",
    title: "Practical Implementation Plan",
    description:
      "Break down a technical or operational objective into sequenced, verifiable implementation phases with rollback triggers.",
    icon: "build",
    sourceHint:
      "Select requirements documents, architecture decision records (ADRs), tickets, or technical specs.",
    outputLabel: "Implementation Plan",
    prompt: [
      "You are building a practical, phased implementation plan. Every step must be concrete, testable, and ordered by dependency.",
      "",
      "## Required Input Needs",
      "- Target objective: [What system, feature, or operational capability is being implemented]",
      "- Source specifications: [Requirements documents, ADRs, interface contracts, or schematics]",
      "- Environment constraints: [Runtime versions, deployment tooling, access limits, team capacity]",
      "",
      "## Evidence & Citation Expectations",
      "- Anchor each phase to specific requirements or design documents using [Req: <ID>] or [ADR: <Title>].",
      "- Reference existing repository conventions, directory layouts, and configuration patterns.",
      "- Do not introduce untracked external dependencies or speculative tooling not justified by the sources.",
      "",
      "## Output Structure",
      "Structure the plan into the following sections:",
      "1. Objectives & Scope of Work: Exact scope boundaries and definition of done (DoD).",
      "2. Pre-flight Checklist & Prerequisites: Tooling, access tokens, branch setup, and database snapshots required prior to start.",
      "3. Phased Execution Roadmap: Sequenced phases (Phase 1, Phase 2, etc.), where each phase defines:",
      "   - Phase goal and dependency gate",
      "   - Discrete tasks with file paths and expected changes",
      "   - Verification command or test for the phase",
      "4. Verification & Testing Matrix: Unit, integration, regression, and end-to-end verification steps.",
      "5. Failure Triggers & Rollback Runbook: Exact threshold criteria that trigger a rollback and step-by-step reversal commands.",
      "6. Risk Register & Mitigations: Technical debt introduced, concurrency risks, and monitoring alarms.",
      "",
      "## Limits & Uncertainty",
      "- Identify tasks whose estimates carry high uncertainty due to legacy code or missing documentation.",
      "- Highlight external service dependencies that could block delivery.",
      "",
      "## Acceptance & Sign-off Questions",
      "Before executing this plan, verify:",
      "- Can each phase be verified independently before proceeding to the subsequent phase?",
      "- Are rollback procedures fully documented with concrete reversal commands?",
      "- Is test coverage established at each phase rather than deferred to the end?"
    ].join("\n")
  },
  {
    id: "data-findings",
    title: "Spreadsheet & Data Findings",
    description:
      "Analyze tabular data, metrics, or financial extracts to extract trends, anomalies, statistical summaries, and data quality caveats.",
    icon: "data",
    sourceHint:
      "Select CSV, TSV, markdown tables, financial summaries, or metrics exports.",
    outputLabel: "Data Findings",
    prompt: [
      "You are analyzing tabular data or metrics to produce an executive data findings report. All statistics must be strictly derived from the provided numbers.",
      "",
      "## Required Input Needs",
      "- Tabular dataset: [CSV, TSV, markdown table, or numerical extract selected in sources]",
      "- Analytical objective: [Key metric, trend, or question to investigate]",
      "- Baseline / Period: [Comparison timeframe, cohort, or baseline benchmark]",
      "",
      "## Evidence & Citation Expectations",
      "- Ground every metric, percentage, or trend in specific rows, columns, or cell ranges from the source data.",
      "- Cite data points using [Row X, Col Y] or [Dataset: <Field>].",
      "- Show calculation logic for any derived metric (e.g., Growth Rate = (Q2 - Q1) / Q1).",
      "- Never interpolate, hallucinate, or smooth over missing data points without explicit notation.",
      "",
      "## Output Structure",
      "Structure the findings into the following sections:",
      "1. Executive Findings & Key Metrics: Top 3-5 quantitative takeaways with directional indicators.",
      "2. Data Hygiene & Quality Audit:",
      "   - Total records, date range, null/missing values count",
      "   - Detected anomalies, outliers, duplicate records, or formatting discrepancies",
      "3. Core Quantitative Analysis:",
      "   - Summary statistics table (Count, Mean, Median, Min, Max, Standard Deviation where applicable)",
      "   - Trend analysis over time or across segments",
      "4. Granular Breakdown & Findings Table: Markdown table detailing specific segment or cohort performance.",
      "5. Business Implications & Hypotheses: What the numbers mean for operations or strategy.",
      "6. Limits, Biases & Missing Dimensions:",
      "   - Sample size limitations, survivorship bias, unmeasured confounding variables",
      "   - Gaps where additional data is required to confirm causality",
      "",
      "## Acceptance & Sign-off Questions",
      "Before accepting this artifact, verify:",
      "- Were all derived calculations cross-checked against the raw data points?",
      "- Are data hygiene limitations and missing records clearly disclosed?",
      "- Does the report avoid claiming causal relationships where only correlation is observed?"
    ].join("\n")
  }
] as const;
