import { CanonicalDurableIdSchema } from "@cadrane/contracts";
import { ApprovedCapabilityIntentSchema, type ApprovedCapabilityIntent } from "@cadrane/contracts/capability-intent";
import { canonicalCapabilityIntentSha256 } from "./capability-intent-binding.js";

const FIELDS = ["schemaVersion","permissionRequestId","permissionDecisionId","spaceId","runId","effectId","effectRevision","effectKind","authoritySessionId","subjectBindingSha256","targetBindingSha256","parameterSha256","requestSha256","expiresAt","maxUses"] as const;
const USE_FIELDS = ["grantId","useId","intentSha256",...FIELDS] as const; const HASH = /^[a-f0-9]{64}$/;
export interface CapabilityApprovalAuthority { approve(intent: Readonly<ApprovedCapabilityIntent>, intentSha256: string): unknown; }
export class CapabilityIntentBrokerError extends Error { readonly code = "CAPABILITY_INTENT_BROKER_FAILED" as const; constructor() { super("Capability intent broker operation failed."); this.name = "CapabilityIntentBrokerError"; } }
interface Grant { readonly id: string; readonly intent: ApprovedCapabilityIntent; readonly digest: string; readonly issuedAt: number; state: "active"|"consumed"|"revoked"|"expired"; }
export class CapabilityIntentBroker {
  private readonly grants = new Map<string, Grant>(); private readonly tuples = new Map<string, string>(); private readonly requests = new Set<string>(); private readonly decisions = new Set<string>(); private readonly uses = new Set<string>(); private lastNow = -1; private busy = false;
  constructor(private readonly authority: CapabilityApprovalAuthority, private readonly now: () => number, private readonly grantId: () => string) {}
  issue(value: unknown): Readonly<{ grantId: string; intentSha256: string; issuedAt: string; intent: ApprovedCapabilityIntent }> { return this.atomic(() => { const intent = decodeIntent(value); const now = this.clock(); const digest = digestIntent(intent); const tuple = `${intent.permissionRequestId}:${intent.permissionDecisionId}`; const prior = this.tuples.get(tuple); const expiry = Date.parse(intent.expiresAt); if (prior !== undefined) { const grant = this.grants.get(prior); if (grant?.state === "active" && grant.digest === digest && Date.parse(grant.intent.expiresAt) <= now) grant.state = "expired"; if (grant?.state === "active" && grant.digest === digest && expiry > now) return projection(grant); throw fail(); } if (expiry <= now || expiry - now > 600_000) throw fail(); if (this.grants.size >= 4096 || this.requests.has(intent.permissionRequestId) || this.decisions.has(intent.permissionDecisionId)) throw fail(); const proof = this.authority.approve(Object.freeze(copyIntent(intent)), digest); if (!proofOk(proof, intent, digest)) throw fail(); const id = this.grantId(); if (!isUuid(id) || this.grants.has(id)) throw fail(); const grant: Grant = { id, intent: Object.freeze(copyIntent(intent)), digest, issuedAt: now, state: "active" }; this.grants.set(id, grant); this.tuples.set(tuple, id); this.requests.add(intent.permissionRequestId); this.decisions.add(intent.permissionDecisionId); return projection(grant); }); }
  authorizeAndConsume(value: unknown) { return this.atomic(() => { const raw = decode(value, USE_FIELDS); const now = this.clock(); if (!isUuid(raw.grantId) || !isUuid(raw.useId) || typeof raw.intentSha256 !== "string" || !HASH.test(raw.intentSha256) || this.uses.has(raw.useId)) throw fail(); const grant = this.grants.get(raw.grantId); if (grant === undefined || grant.state !== "active" || grant.digest !== raw.intentSha256 || Date.parse(grant.intent.expiresAt) <= now) { if (grant !== undefined && Date.parse(grant.intent.expiresAt) <= now) grant.state = "expired"; throw fail(); } const supplied = decodeIntent(fieldsOnly(raw)); if (digestIntent(supplied) !== grant.digest) throw fail(); this.uses.add(raw.useId); grant.state = "consumed"; return Object.freeze({ schemaVersion: 1 as const, grantId: grant.id, useId: raw.useId, intentSha256: grant.digest, issuedAt: new Date(grant.issuedAt).toISOString(), claimedAt: new Date(now).toISOString(), intent: Object.freeze(copyIntent(grant.intent)), decision:"allow" as const, consumed:true as const, effectExecution:"not-performed" as const }); }); }
  revoke(value: unknown) { return this.atomic(() => { const now = this.clock(); const raw = decode(value, ["grantId","authoritySessionId","intentSha256"]); if (!isUuid(raw.grantId) || !isUuid(raw.authoritySessionId) || typeof raw.intentSha256 !== "string" || !HASH.test(raw.intentSha256)) throw fail(); const grant = this.grants.get(raw.grantId); if (grant !== undefined && Date.parse(grant.intent.expiresAt) <= now) grant.state = "expired"; if (grant === undefined || grant.state !== "active" || raw.authoritySessionId !== grant.intent.authoritySessionId || raw.intentSha256 !== grant.digest) throw fail(); grant.state = "revoked"; return Object.freeze({ schemaVersion: 1 as const, grantId: grant.id, intentSha256: grant.digest, revoked: true as const, revokedAt: new Date(now).toISOString(), intent: Object.freeze(copyIntent(grant.intent)), effectExecution: "not-performed" as const }); }); }
  private atomic<T>(operation: () => T): T { if (this.busy) throw fail(); this.busy = true; try { return operation(); } catch (_e) { throw fail(); } finally { this.busy = false; } }
  private clock(): number { const value = this.now(); if (!Number.isSafeInteger(value) || value < 0 || value > 8_640_000_000_000_000 || value < this.lastNow) throw fail(); this.lastNow = value; return value; }
}
function decodeIntent(value: unknown): ApprovedCapabilityIntent { const raw = decode(value, FIELDS); const intent = ApprovedCapabilityIntentSchema.safeParse(raw); if (!intent.success || !FIELDS.filter((key) => key.endsWith("Id")).every((key) => isUuid(raw[key])) || !["subjectBindingSha256","targetBindingSha256","parameterSha256","requestSha256"].every((key) => typeof raw[key] === "string" && HASH.test(raw[key]))) throw fail(); return Object.freeze(copyIntent(intent.data)); }
function decode(value: unknown, fields: readonly string[]): Record<string, unknown> { if (!plain(value, fields)) throw fail(); const raw = value as Record<string, unknown>; const out: Record<string, unknown> = {}; for (const field of fields) out[field] = Object.getOwnPropertyDescriptor(raw, field)?.value; return out; }
function plain(value: unknown, fields: readonly string[]): boolean { try { if (value === null || typeof value !== "object" || Object.getPrototypeOf(value) !== Object.prototype) return false; const keys = Reflect.ownKeys(value); return keys.length === fields.length && fields.every((field) => { const d = Object.getOwnPropertyDescriptor(value, field); return d !== undefined && Object.hasOwn(d, "value"); }); } catch { return false; } }
function fieldsOnly(value: Record<string, unknown>): Record<string, unknown> { const out: Record<string, unknown> = {}; for (const key of FIELDS) out[key] = value[key]; return out; }
function digestIntent(intent: ApprovedCapabilityIntent): string { return canonicalCapabilityIntentSha256(intent); }
function proofOk(value: unknown, intent: ApprovedCapabilityIntent, digest: string): boolean { try { const raw = decode(value, ["verdict","permissionRequestId","permissionDecisionId","authoritySessionId","requestSha256","intentSha256","expiresAt"]); return raw.verdict === "approved" && raw.permissionRequestId === intent.permissionRequestId && raw.permissionDecisionId === intent.permissionDecisionId && raw.authoritySessionId === intent.authoritySessionId && raw.requestSha256 === intent.requestSha256 && raw.intentSha256 === digest && raw.expiresAt === intent.expiresAt; } catch { return false; } }
function projection(grant: Grant) { return Object.freeze({ grantId: grant.id, intentSha256: grant.digest, issuedAt: new Date(grant.issuedAt).toISOString(), intent: Object.freeze(copyIntent(grant.intent)) }); }
function copyIntent(intent: ApprovedCapabilityIntent): ApprovedCapabilityIntent { return { ...intent }; }
function isUuid(value: unknown): value is string { return CanonicalDurableIdSchema.safeParse(value).success; } function fail(): CapabilityIntentBrokerError { return new CapabilityIntentBrokerError(); }
