import { createHash } from "node:crypto";
import { types } from "node:util";
import { CanonicalDurableIdSchema } from "@cadrane/contracts";
import { DurableEffectSchema, DurableJournalEventSchema, type DurableEffect, type DurableJournalEvent, type DurableJournalRecord } from "@cadrane/contracts/durable-journal";
import { type AsyncTransactionalPersistencePortForTestOnly } from "./async-transactional-persistence-filesystem-port.js";
import { InMemoryWorkStore, type InMemoryWorkStoreImage } from "./in-memory-work-store.js";
import { enqueueTransactionalPortOperation } from "./transactional-port-queue.js";
import { TransactionalPersistenceError, disposeOpaqueJournalSnapshotForTestOnly, operationBindingSha256ForDurableRecordSetForTestOnly, restoreInMemoryWorkStoreFromSnapshotForTestOnly, snapshotFromInMemoryWorkStoreForTestOnly, validateRecoveredTransactionalStateForTestOnly, type OpaqueJournalSnapshot, type RecoveredTransactionalState, type TransactionReceipt } from "./transactional-persistence.js";

const HASH = /^[a-f0-9]{64}$/u;
type Transition = "record-run" | "create-pending-effect";
interface OperationPrerequisites { readonly runOperationId: string; readonly runOperationBindingSha256: string; readonly anchorOperationId: string | null; readonly anchorOperationBindingSha256: string | null; }
export interface InertRunRecordedResult { readonly event: DurableJournalEvent; readonly effect: null; readonly effectExecution: "not-performed"; }
export interface InertPendingEffectResult { readonly event: DurableJournalEvent; readonly effect: DurableEffect; readonly effectExecution: "not-performed"; }
export class AsyncTransactionalInertEventEffectJournalError extends Error { readonly code = "ASYNC_TRANSACTIONAL_INERT_EVENT_EFFECT_JOURNAL_FAILED" as const; constructor() { super("Async transactional inert event effect journal operation failed."); this.name = "AsyncTransactionalInertEventEffectJournalError"; } }

/** Private, inert transcript writer. It has no authority beyond metadata publication. */
export class AsyncTransactionalInertEventEffectJournal {
  private readonly identity: object;
  constructor(private readonly port: AsyncTransactionalPersistencePortForTestOnly) { try { const identity = port.concurrencyIdentity; if (identity === null || typeof identity !== "object" || types.isProxy(identity)) throw failed(); this.identity = identity; } catch { throw failed(); } }

  async recordRun(input: unknown): Promise<InertRunRecordedResult> {
    let owned: OwnedRun | undefined;
    try { owned = parseRun(input); return await enqueueTransactionalPortOperation(this.identity, () => this.recordRunOwned(owned!)); }
    catch { throw failed(); }
  }

  async createPendingEffect(input: unknown): Promise<InertPendingEffectResult> {
    let owned: OwnedEffect | undefined;
    try { owned = parseEffectInput(input); return await enqueueTransactionalPortOperation(this.identity, () => this.createPendingEffectOwned(owned!)); }
    catch { throw failed(); }
  }

  private async recordRunOwned(owned: OwnedRun): Promise<InertRunRecordedResult> {
    let raw: RecoveredTransactionalState | undefined; let recovered: RecoveredTransactionalState | undefined; let store: InMemoryWorkStore | undefined; let staged: OpaqueJournalSnapshot | undefined; let verifiedRaw: RecoveredTransactionalState | undefined; let verified: RecoveredTransactionalState | undefined; let verifier: InMemoryWorkStore | undefined;
    try {
      ({ raw, validated: recovered } = await recover(this.port)); assertInert(recovered!); const run = requireRun(recovered!, owned); const runBinding = await requireRecordBinding(this.port, owned.runOperationId, run); const prerequisites = recordPrerequisites(owned.runOperationId, runBinding);
      const event = runEvent(owned); const binding = inertEventEffectOperationBindingSha256ForTestOnly("record-run", owned.operationId, event, null, prerequisites); const existing = eventById(recovered!, owned.operationId);
      if (existing !== undefined) { if (!same(existing, event)) throw failed(); await requireBinding(this.port, owned.operationId, binding); return runResult(existing); }
      if (await this.port.recoverOperationBinding(owned.operationId) !== undefined) throw failed();
      store = restoreInMemoryWorkStoreFromSnapshotForTestOnly(recovered!.snapshot); const appended = store.appendEvent(event); if (!same(appended, event)) throw failed();
      staged = snapshotFromInMemoryWorkStoreForTestOnly(store); const receipt = await commitOnce(this.port, Object.freeze({ commitId: owned.operationId, expectedGeneration: recovered!.generation, expectedSnapshotSha256: recovered!.snapshotSha256, operationBindingSha256: binding, snapshot: staged }), owned.operationId, recovered!.generation + 1);
      ({ raw: verifiedRaw, validated: verified } = await recover(this.port)); if (verified!.generation !== receipt.generation || verified!.snapshotSha256 !== receipt.snapshotSha256) throw failed(); assertInert(verified!); const verifiedRun = requireRun(verified!, owned); const verifiedRunBinding = await requireRecordBinding(this.port, owned.runOperationId, verifiedRun); const verifiedBinding = inertEventEffectOperationBindingSha256ForTestOnly("record-run", owned.operationId, event, null, recordPrerequisites(owned.runOperationId, verifiedRunBinding)); if (verifiedBinding !== binding) throw failed(); await requireBinding(this.port, owned.operationId, verifiedBinding);
      verifier = restoreInMemoryWorkStoreFromSnapshotForTestOnly(verified!.snapshot); const adopted = eventById(verified!, owned.operationId); if (adopted === undefined || !same(adopted, event) || verifier === undefined) throw failed(); return runResult(adopted);
    } catch { throw failed(); }
    finally { store?.disposeForTestOnly(); verifier?.disposeForTestOnly(); disposeOpaqueJournalSnapshotForTestOnly(raw?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(recovered?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(staged); disposeOpaqueJournalSnapshotForTestOnly(verifiedRaw?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(verified?.snapshot); }
  }

  private async createPendingEffectOwned(owned: OwnedEffect): Promise<InertPendingEffectResult> {
    let raw: RecoveredTransactionalState | undefined; let recovered: RecoveredTransactionalState | undefined; let store: InMemoryWorkStore | undefined; let bridge: InMemoryWorkStoreImage | undefined; let deterministic: InMemoryWorkStore | undefined; let staged: OpaqueJournalSnapshot | undefined; let verifiedRaw: RecoveredTransactionalState | undefined; let verified: RecoveredTransactionalState | undefined; let verifier: InMemoryWorkStore | undefined;
    try {
      ({ raw, validated: recovered } = await recover(this.port)); assertInert(recovered!); const run = requireEffectRun(recovered!, owned); const runBinding = await requireRecordBinding(this.port, owned.runOperationId, run); const anchor = requireAnchor(recovered!, owned, run); const anchorBinding = inertEventEffectOperationBindingSha256ForTestOnly("record-run", anchor.id, anchor, null, recordPrerequisites(owned.runOperationId, runBinding)); await requireBinding(this.port, anchor.id, anchorBinding); const prerequisites = createPrerequisites(owned.runOperationId, runBinding, anchor.id, anchorBinding);
      const event = effectEvent(owned, run.envelope.ciphertextSha256); const binding = inertEventEffectOperationBindingSha256ForTestOnly("create-pending-effect", owned.operationId, event, owned.effect, prerequisites); const existingEffect = effectById(recovered!, owned.effect.id); const existingEvent = eventById(recovered!, owned.operationId); const aliases = recovered!.snapshot.journal.effects.filter((value) => value.spaceId === owned.effect.spaceId && value.runId === owned.effect.runId && value.runRevision === owned.effect.runRevision && value.stepKey === owned.effect.stepKey && value.requestSha256 === owned.effect.requestSha256);
      const transcript = recovered!.snapshot.journal.events.filter((value) => value.effectId === owned.effect.id);
      if (existingEffect !== undefined || existingEvent !== undefined) { if (existingEffect === undefined || existingEvent === undefined || !same(existingEffect, owned.effect) || !same(existingEvent, event) || aliases.length !== 1 || transcript.length !== 1 || !same(transcript[0], event)) throw failed(); await requireBinding(this.port, owned.operationId, binding); return effectResult(existingEvent, existingEffect); }
      if (aliases.length !== 0 || transcript.length !== 0 || await this.port.recoverOperationBinding(owned.operationId) !== undefined) throw failed();
      store = restoreInMemoryWorkStoreFromSnapshotForTestOnly(recovered!.snapshot); bridge = store.exportImageForTestOnly(); let issued = false; deterministic = new InMemoryWorkStore(() => { throw failed(); }, () => { if (issued) throw failed(); issued = true; return owned.operationId; }); deterministic.restoreImageForTestOnly(bridge); wipeBridge(bridge); bridge = undefined; store.disposeForTestOnly(); store = undefined;
      const created = deterministic.putEffect(owned.effect); if (!issued || !same(created, owned.effect)) throw failed(); staged = snapshotFromInMemoryWorkStoreForTestOnly(deterministic); const receipt = await commitOnce(this.port, Object.freeze({ commitId: owned.operationId, expectedGeneration: recovered!.generation, expectedSnapshotSha256: recovered!.snapshotSha256, operationBindingSha256: binding, snapshot: staged }), owned.operationId, recovered!.generation + 1);
      ({ raw: verifiedRaw, validated: verified } = await recover(this.port)); if (verified!.generation !== receipt.generation || verified!.snapshotSha256 !== receipt.snapshotSha256) throw failed(); assertInert(verified!); const verifiedRun = requireEffectRun(verified!, owned); const verifiedRunBinding = await requireRecordBinding(this.port, owned.runOperationId, verifiedRun); const verifiedAnchor = requireAnchor(verified!, owned, verifiedRun); const verifiedAnchorBinding = inertEventEffectOperationBindingSha256ForTestOnly("record-run", verifiedAnchor.id, verifiedAnchor, null, recordPrerequisites(owned.runOperationId, verifiedRunBinding)); await requireBinding(this.port, verifiedAnchor.id, verifiedAnchorBinding); const verifiedBinding = inertEventEffectOperationBindingSha256ForTestOnly("create-pending-effect", owned.operationId, event, owned.effect, createPrerequisites(owned.runOperationId, verifiedRunBinding, verifiedAnchor.id, verifiedAnchorBinding)); if (verifiedBinding !== binding) throw failed(); await requireBinding(this.port, owned.operationId, verifiedBinding);
      verifier = restoreInMemoryWorkStoreFromSnapshotForTestOnly(verified!.snapshot); const adoptedEffect = effectById(verified!, owned.effect.id); const adoptedEvent = eventById(verified!, owned.operationId); if (adoptedEffect === undefined || adoptedEvent === undefined || !same(adoptedEffect, owned.effect) || !same(adoptedEvent, event) || verifier === undefined) throw failed(); return effectResult(adoptedEvent, adoptedEffect);
    } catch { throw failed(); }
    finally { store?.disposeForTestOnly(); deterministic?.disposeForTestOnly(); verifier?.disposeForTestOnly(); wipeBridge(bridge); disposeOpaqueJournalSnapshotForTestOnly(raw?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(recovered?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(staged); disposeOpaqueJournalSnapshotForTestOnly(verifiedRaw?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(verified?.snapshot); }
  }
}

export function inertEventEffectOperationBindingSha256ForTestOnly(transition: Transition, operationId: string, event: unknown, effect: unknown, prerequisites: unknown): string {
  try { if ((transition !== "record-run" && transition !== "create-pending-effect") || !validId(operationId)) throw failed(); const parsedEvent = copyEvent(event); const parsedEffect = effect === null ? null : copyEffect(effect); const parsedPrerequisites = copyPrerequisites(prerequisites); if (transition === "record-run" ? parsedEffect !== null || parsedEvent.kind !== "run-recorded" || parsedEvent.id !== operationId || parsedPrerequisites.anchorOperationId !== null || parsedPrerequisites.anchorOperationBindingSha256 !== null : parsedEffect === null || parsedEvent.kind !== "effect-created" || parsedEvent.id !== operationId || parsedEvent.spaceId !== parsedEffect.spaceId || parsedEvent.runId !== parsedEffect.runId || parsedEvent.runRevision !== parsedEffect.runRevision || parsedEvent.effectId !== parsedEffect.id || parsedEvent.effectRevision !== 1 || parsedEvent.effectState !== "pending" || parsedEvent.claimSha256 !== null || parsedEffect.state !== "pending" || parsedEffect.effectRevision !== 1 || parsedEffect.claimId !== null || parsedPrerequisites.anchorOperationId === null || parsedPrerequisites.anchorOperationBindingSha256 === null) throw failed(); return createHash("sha256").update(`async-transactional-inert-event-effect-journal:v2:${JSON.stringify({ transition, operationId, prerequisites: canonicalPrerequisites(parsedPrerequisites), event: canonicalEvent(parsedEvent), effect: parsedEffect === null ? null : canonicalEffect(parsedEffect) })}`).digest("hex"); } catch { throw failed(); }
}

interface OwnedRun { readonly operationId: string; readonly runOperationId: string; readonly spaceId: string; readonly runId: string; readonly runRevision: number; readonly runCiphertextSha256: string; }
interface OwnedEffect { readonly operationId: string; readonly runOperationId: string; readonly effect: DurableEffect; }
async function recover(port: AsyncTransactionalPersistencePortForTestOnly): Promise<{ readonly raw: RecoveredTransactionalState; readonly validated: RecoveredTransactionalState }> { let raw: RecoveredTransactionalState | undefined; let validated: RecoveredTransactionalState | undefined; try { raw = await port.recover(); validated = validateRecoveredTransactionalStateForTestOnly(raw); return Object.freeze({ raw, validated }); } catch { disposeOpaqueJournalSnapshotForTestOnly(raw?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(validated?.snapshot); throw failed(); } }
function assertInert(state: RecoveredTransactionalState): void { if (state.snapshot.issuedClaims.some((entry) => entry.claimIds.length !== 0)) throw failed(); for (const effect of state.snapshot.journal.effects) if (effect.state !== "pending" || effect.effectRevision !== 1 || effect.claimId !== null) throw failed(); for (const event of state.snapshot.journal.events) if (event.kind !== "run-recorded" && event.kind !== "effect-created") throw failed(); }
function requireRun(state: RecoveredTransactionalState, input: OwnedRun): DurableJournalRecord { const run = state.snapshot.journal.records.find((record) => record.id === input.runId && record.recordRevision === input.runRevision); if (run === undefined || run.spaceId !== input.spaceId || run.idempotency.kind !== "run" || run.envelope.ciphertextSha256 !== input.runCiphertextSha256) throw failed(); return run; }
function requireEffectRun(state: RecoveredTransactionalState, input: OwnedEffect): DurableJournalRecord { const run = state.snapshot.journal.records.find((record) => record.id === input.effect.runId && record.recordRevision === input.effect.runRevision); if (run === undefined || run.spaceId !== input.effect.spaceId || run.idempotency.kind !== "run") throw failed(); return run; }
function requireAnchor(state: RecoveredTransactionalState, input: OwnedEffect, run: DurableJournalRecord): DurableJournalEvent { const anchor = state.snapshot.journal.events.find((event) => event.runId === input.effect.runId && event.sequence === 1); if (anchor === undefined || anchor.kind !== "run-recorded" || anchor.spaceId !== input.effect.spaceId || anchor.runRevision !== input.effect.runRevision || anchor.runCiphertextSha256 !== run.envelope.ciphertextSha256 || anchor.effectId !== null || anchor.effectRevision !== null || anchor.effectState !== null || anchor.claimSha256 !== null) throw failed(); return anchor; }
async function requireRecordBinding(port: AsyncTransactionalPersistencePortForTestOnly, operationId: string, record: DurableJournalRecord): Promise<string> { const binding = operationBindingSha256ForDurableRecordSetForTestOnly([record]); await requireBinding(port, operationId, binding); return binding; }
async function requireBinding(port: AsyncTransactionalPersistencePortForTestOnly, operationId: string, expected: string): Promise<void> { try { const raw = exact(await port.recoverOperationBinding(operationId), ["commitId", "operationBindingSha256"]); if (raw === undefined || raw.commitId !== operationId || raw.operationBindingSha256 !== expected || !hash(raw.operationBindingSha256)) throw failed(); } catch { throw failed(); } }
async function commitOnce(port: AsyncTransactionalPersistencePortForTestOnly, request: unknown, operationId: string, generation: number): Promise<TransactionReceipt> { try { return receipt(await port.commit(request), operationId, generation); } catch (error) { if (!(error instanceof TransactionalPersistenceError) || error.code !== "INTERRUPTED") throw error; return receipt(await port.commit(request), operationId, generation); } }
function receipt(value: unknown, operationId: string, generation: number): TransactionReceipt { const raw = exact(value, ["commitId", "generation", "snapshotSha256"]); if (raw === undefined || raw.commitId !== operationId || raw.generation !== generation || !hash(raw.snapshotSha256)) throw failed(); return Object.freeze({ commitId: operationId, generation, snapshotSha256: raw.snapshotSha256 as string }); }
function parseRun(value: unknown): OwnedRun { const raw = exact(value, ["operationId", "runOperationId", "spaceId", "runId", "runRevision", "runCiphertextSha256"]); if (raw === undefined || !validId(raw.operationId) || !validId(raw.runOperationId) || !validId(raw.spaceId) || !validId(raw.runId) || !revision(raw.runRevision) || !hash(raw.runCiphertextSha256)) throw failed(); return Object.freeze({ operationId: raw.operationId, runOperationId: raw.runOperationId, spaceId: raw.spaceId, runId: raw.runId, runRevision: raw.runRevision, runCiphertextSha256: raw.runCiphertextSha256 }); }
function parseEffectInput(value: unknown): OwnedEffect { const raw = exact(value, ["operationId", "runOperationId", "effect"]); if (raw === undefined || !validId(raw.operationId) || !validId(raw.runOperationId)) throw failed(); const effect = copyEffect(raw.effect); if (effect.state !== "pending" || effect.effectRevision !== 1 || effect.claimId !== null) throw failed(); return Object.freeze({ operationId: raw.operationId, runOperationId: raw.runOperationId, effect }); }
function copyEvent(value: unknown): DurableJournalEvent { const raw = exact(value, ["schemaVersion", "id", "spaceId", "runId", "runRevision", "sequence", "kind", "runCiphertextSha256", "effectId", "effectRevision", "effectState", "claimSha256"]); if (raw === undefined) throw failed(); const parsed = DurableJournalEventSchema.safeParse({ schemaVersion: raw.schemaVersion, id: raw.id, spaceId: raw.spaceId, runId: raw.runId, runRevision: raw.runRevision, sequence: raw.sequence, kind: raw.kind, runCiphertextSha256: raw.runCiphertextSha256, effectId: raw.effectId, effectRevision: raw.effectRevision, effectState: raw.effectState, claimSha256: raw.claimSha256 }); if (!parsed.success) throw failed(); return parsed.data; }
function copyEffect(value: unknown): DurableEffect { const raw = exact(value, ["schemaVersion", "id", "spaceId", "runId", "runRevision", "stepKey", "requestSha256", "state", "effectRevision", "claimId"]); if (raw === undefined) throw failed(); const parsed = DurableEffectSchema.safeParse({ schemaVersion: raw.schemaVersion, id: raw.id, spaceId: raw.spaceId, runId: raw.runId, runRevision: raw.runRevision, stepKey: raw.stepKey, requestSha256: raw.requestSha256, state: raw.state, effectRevision: raw.effectRevision, claimId: raw.claimId }); if (!parsed.success) throw failed(); return parsed.data; }
function copyPrerequisites(value: unknown): OperationPrerequisites { const raw = exact(value, ["runOperationId", "runOperationBindingSha256", "anchorOperationId", "anchorOperationBindingSha256"]); if (raw === undefined || !validId(raw.runOperationId) || !hash(raw.runOperationBindingSha256) || !(raw.anchorOperationId === null || validId(raw.anchorOperationId)) || !(raw.anchorOperationBindingSha256 === null || hash(raw.anchorOperationBindingSha256)) || (raw.anchorOperationId === null)!==(raw.anchorOperationBindingSha256 === null)) throw failed(); return Object.freeze({ runOperationId: raw.runOperationId, runOperationBindingSha256: raw.runOperationBindingSha256, anchorOperationId: raw.anchorOperationId, anchorOperationBindingSha256: raw.anchorOperationBindingSha256 }); }
function recordPrerequisites(runOperationId: string, runOperationBindingSha256: string): OperationPrerequisites { return Object.freeze({ runOperationId, runOperationBindingSha256, anchorOperationId: null, anchorOperationBindingSha256: null }); }
function createPrerequisites(runOperationId: string, runOperationBindingSha256: string, anchorOperationId: string, anchorOperationBindingSha256: string): OperationPrerequisites { return Object.freeze({ runOperationId, runOperationBindingSha256, anchorOperationId, anchorOperationBindingSha256 }); }
function runEvent(input: OwnedRun): DurableJournalEvent { return DurableJournalEventSchema.parse({ schemaVersion: 1, id: input.operationId, spaceId: input.spaceId, runId: input.runId, runRevision: input.runRevision, sequence: 1, kind: "run-recorded", runCiphertextSha256: input.runCiphertextSha256, effectId: null, effectRevision: null, effectState: null, claimSha256: null }); }
function effectEvent(input: OwnedEffect, runCiphertextSha256: string): DurableJournalEvent { const effect = input.effect; return DurableJournalEventSchema.parse({ schemaVersion: 1, id: input.operationId, spaceId: effect.spaceId, runId: effect.runId, runRevision: effect.runRevision, sequence: 2, kind: "effect-created", runCiphertextSha256, effectId: effect.id, effectRevision: 1, effectState: "pending", claimSha256: null }); }
function eventById(state: RecoveredTransactionalState, id: string): DurableJournalEvent | undefined { return state.snapshot.journal.events.find((event) => event.id === id); }
function effectById(state: RecoveredTransactionalState, id: string): DurableEffect | undefined { return state.snapshot.journal.effects.find((effect) => effect.id === id); }
function runResult(event: DurableJournalEvent): InertRunRecordedResult { return deepFreeze({ event: JSON.parse(JSON.stringify(event)) as DurableJournalEvent, effect: null, effectExecution: "not-performed" as const }); }
function effectResult(event: DurableJournalEvent, effect: DurableEffect): InertPendingEffectResult { return deepFreeze({ event: JSON.parse(JSON.stringify(event)) as DurableJournalEvent, effect: JSON.parse(JSON.stringify(effect)) as DurableEffect, effectExecution: "not-performed" as const }); }
function exact(value: unknown, fields: readonly string[]): Record<string, unknown> | undefined { try { if (value === null || typeof value !== "object" || types.isProxy(value) || Object.getPrototypeOf(value) !== Object.prototype) return undefined; let count = 0; for (const key in value) { if (!Object.hasOwn(value, key) || !fields.includes(key) || ++count > fields.length) return undefined; } if (count !== fields.length) return undefined; const out: Record<string, unknown> = {}; for (const field of fields) { const descriptor = Object.getOwnPropertyDescriptor(value, field); if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor)) return undefined; out[field] = descriptor.value; } return out; } catch { return undefined; } }
function validId(value: unknown): value is string { return CanonicalDurableIdSchema.safeParse(value).success; }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function revision(value: unknown): value is number { return Number.isSafeInteger(value) && (value as number) > 0; }
function same(left: unknown, right: unknown): boolean { return JSON.stringify(left) === JSON.stringify(right); }
function wipeBridge(image: InMemoryWorkStoreImage | undefined): void { image?.envelopes.forEach((entry) => entry.ciphertext.fill(0)); }
function canonicalEvent(value: DurableJournalEvent): object { return { schemaVersion: value.schemaVersion, id: value.id, spaceId: value.spaceId, runId: value.runId, runRevision: value.runRevision, sequence: value.sequence, kind: value.kind, runCiphertextSha256: value.runCiphertextSha256, effectId: value.effectId, effectRevision: value.effectRevision, effectState: value.effectState, claimSha256: value.claimSha256 }; }
function canonicalEffect(value: DurableEffect): object { return { schemaVersion: value.schemaVersion, id: value.id, spaceId: value.spaceId, runId: value.runId, runRevision: value.runRevision, stepKey: value.stepKey, requestSha256: value.requestSha256, state: value.state, effectRevision: value.effectRevision, claimId: value.claimId }; }
function canonicalPrerequisites(value: OperationPrerequisites): object { return { runOperationId: value.runOperationId, runOperationBindingSha256: value.runOperationBindingSha256, anchorOperationId: value.anchorOperationId, anchorOperationBindingSha256: value.anchorOperationBindingSha256 }; }
function deepFreeze<T>(value: T): T { if (value !== null && typeof value === "object") { for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); Object.freeze(value); } return value; }
function failed(): AsyncTransactionalInertEventEffectJournalError { return new AsyncTransactionalInertEventEffectJournalError(); }
