import { chmod, mkdtemp, rm, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { canonicalCapabilityIntentSha256 } from "../capability-intent-binding.js";
import { prepareIssuedCapabilityJournal, prepareTerminalCapabilityJournal } from "../capability-journal-codec.js";
import { AsyncTransactionalCapabilityJournal, AsyncTransactionalCapabilityJournalError } from "./async-transactional-capability-journal.js";
import { AsyncTransactionalEncryptedWorkSet, AsyncTransactionalEncryptedWorkSetError } from "./async-transactional-encrypted-work-set.js";
import { AsyncTransactionalPersistenceFilesystemPortForTestOnly, type AsyncTransactionalPersistencePortForTestOnly } from "./async-transactional-persistence-filesystem-port.js";
import { type WorkspaceKeyProvider } from "./encrypted-work-store.js";
import { disposeTransactionalPersistenceMediumImageForTestOnly } from "./transactional-persistence-image-codec.js";
import { InMemoryTransactionalPersistenceMedium, TransactionalPersistenceError, disposeOpaqueJournalSnapshotForTestOnly, operationBindingSha256ForDurableRecordSetForTestOnly, type RecoveredTransactionalState, type TransactionalPersistenceMediumImage } from "./transactional-persistence.js";
import { TransactionalPersistenceFilesystemForTestOnly, closeTrustedAppOwnedGenerationRootForTestOnly, openTrustedAppOwnedGenerationRootForTestOnly, type TrustedAppOwnedGenerationRootForTestOnly } from "./transactional-persistence-filesystem.js";

const id = (value: number) => `00000000-0000-4000-8000-${value.toString().padStart(12, "0")}`;
const HASH = "a".repeat(64);
const roots: Array<{ readonly path: string; readonly root: TrustedAppOwnedGenerationRootForTestOnly }> = [];
afterEach(async () => { for (const item of roots.splice(0)) { await closeTrustedAppOwnedGenerationRootForTestOnly(item.root); await rm(item.path, { recursive: true, force: true }); } });
async function fixture(): Promise<TrustedAppOwnedGenerationRootForTestOnly> { const path = await mkdtemp("/private/tmp/switchboard-t2p-a4-"); await chmod(path, 0o700); const root = await openTrustedAppOwnedGenerationRootForTestOnly(path); roots.push({ path, root }); return root; }
function issued() { const intent = { schemaVersion: 1, permissionRequestId: id(1), permissionDecisionId: id(2), spaceId: id(3), runId: id(4), effectId: id(5), effectRevision: 1, effectKind: "export-artifact", authoritySessionId: id(6), subjectBindingSha256: HASH, targetBindingSha256: HASH, parameterSha256: HASH, requestSha256: HASH, expiresAt: "2026-08-03T00:05:00.000Z", maxUses: 1 } as const; return prepareIssuedCapabilityJournal({ grantRecordId: id(15), grantId: id(7), intent, approvalEvidence: { schemaVersion: 1, kind: "capability-approval-evidence", verifierId: id(8), verdict: "approved", permissionRequestId: id(1), permissionDecisionId: id(2), authoritySessionId: id(6), requestSha256: HASH, intentSha256: canonicalCapabilityIntentSha256(intent), expiresAt: intent.expiresAt }, issuedAt: "2026-08-03T00:00:00.000Z", issueLifecycleId: id(9), issueOperationId: id(10), issueReceiptId: id(11) }); }
function terminal() { const prior = issued(); return prepareTerminalCapabilityJournal({ predecessor: { state: prior.state, receipt: prior.receipt }, lifecycle: "consumed", lifecycleId: id(12), operationId: id(13), receiptId: id(14), recordedAt: "2026-08-03T00:04:59.999Z" }); }
function keyProvider(state: { active?: boolean; calls?: number; block?: Promise<void>; entered?: () => void; reject?: boolean } = {}): WorkspaceKeyProvider { return { async withUnlockedKey(_reference, callback) { state.calls = (state.calls ?? 0) + 1; state.entered?.(); if (state.block !== undefined) await state.block; if (state.active === false || state.reject === true) throw new Error("locked"); const key = new Uint8Array(32).fill(7); try { await callback(key); } finally { key.fill(0); } } }; }
function journal(port: AsyncTransactionalPersistencePortForTestOnly, firstRef = 100): AsyncTransactionalCapabilityJournal { let ref = firstRef; return new AsyncTransactionalCapabilityJournal(port, keyProvider(), () => id(ref++)); }
function input(operationId = id(50), text = "value") { return { operationId, spaceId: id(3), keyId: id(20), writes: [{ id: id(30), entityKind: "artifact" as const, recordRevision: 1, idempotency: { kind: "entity" as const }, kind: "payload" as const, plaintext: new Uint8Array(Buffer.from(text)) }] }; }
function deferred<T>() { let resolve: (value: T) => void = () => undefined; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; }
async function inspect<T>(port: AsyncTransactionalPersistencePortForTestOnly, read: (state: RecoveredTransactionalState) => T): Promise<T> { const state = await port.recover(); try { return read(state); } finally { disposeOpaqueJournalSnapshotForTestOnly(state.snapshot); } }
const generation = (port: AsyncTransactionalPersistencePortForTestOnly) => inspect(port, (state) => state.generation);

describe("private async encrypted capability-journal coordinator", () => {
  it("issues four encrypted records, exact-replays after restart, terminalizes two records, and exact-replays after a second restart", async () => {
    const root = await fixture(); const first = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const initial = issued(); const end = terminal(); const issue = await journal(first).issue({ spaceId: id(3), keyId: id(20), bundle: initial });
    expect(issue).toHaveLength(4); expect(await generation(first)).toBe(1); await first.close();
    const second = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const replayIssue = await journal(second, 200).issue({ spaceId: id(3), keyId: id(20), bundle: initial }); expect(replayIssue).toEqual(issue); expect(await generation(second)).toBe(1);
    const terminalRecords = await journal(second, 300).terminalize({ spaceId: id(3), keyId: id(20), bundle: end }); expect(terminalRecords).toHaveLength(2); expect(await generation(second)).toBe(2); await second.close();
    const third = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); expect(await journal(third, 400).terminalize({ spaceId: id(3), keyId: id(20), bundle: end })).toEqual(terminalRecords); expect(await inspect(third, (state) => [state.generation, state.snapshot.journal.records.length, state.snapshot.ciphertextBlobs.length])).toEqual([2, 6, 6]); await third.close();
  });

  it("captures caller bytes before await and contains unavailable provider publication before filesystem mutation", async () => {
    const root = await fixture(); const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const blocked = deferred<void>(); const entered = deferred<void>(); const state = { block: blocked.promise, entered: () => entered.resolve() }; let refs = 500; const set = new AsyncTransactionalEncryptedWorkSet(port, keyProvider(state), () => id(refs++));
    const mutable = input(id(51), "owned"); const pending = set.putAtomic(mutable); await entered.promise; mutable.writes[0]!.plaintext.fill(0); blocked.resolve(); await expect(pending).resolves.toHaveLength(1); expect(await generation(port)).toBe(1);
    const inactive = new AsyncTransactionalEncryptedWorkSet(port, keyProvider({ active: false })); await expect(inactive.putAtomic(input(id(52)))).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); expect(await generation(port)).toBe(1); await port.close();
  });

  it("has fully exited the key callback before the A3 filesystem publication boundary", async () => {
    const root = await fixture(); const filesystem = new TransactionalPersistenceFilesystemForTestOnly(root); let active = false; let publications = 0;
    const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root, () => ({ loadLatest: () => filesystem.loadLatest(), publish: async (image) => { publications += 1; expect(active).toBe(false); return filesystem.publish(image); } }));
    const provider: WorkspaceKeyProvider = { async withUnlockedKey(_reference, callback) { const key = new Uint8Array(32).fill(7); active = true; try { await callback(key); } finally { active = false; key.fill(0); } } };
    await expect(new AsyncTransactionalEncryptedWorkSet(port, provider, () => id(450)).putAtomic(input(id(451)))).resolves.toHaveLength(1); expect(publications).toBe(2); await port.close();
  });

  it("fails missing, wrong, reversed, and subset issue replay bindings before provider or ref allocation", async () => {
    const root = await fixture(); const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const start = issued(); await journal(port).issue({ spaceId: id(3), keyId: id(20), bundle: start }); const records = await inspect(port, (state) => state.snapshot.journal.records.map((record) => JSON.parse(JSON.stringify(record)))); const expected = operationBindingSha256ForDurableRecordSetForTestOnly(records);
    for (const projection of [undefined, "0".repeat(64), operationBindingSha256ForDurableRecordSetForTestOnly([...records].reverse()), operationBindingSha256ForDurableRecordSetForTestOnly(records.slice(1))]) { let providers = 0; let refs = 0; const provider: WorkspaceKeyProvider = { async withUnlockedKey(_reference, callback) { providers += 1; await callback(new Uint8Array(32).fill(7)); } }; const wrapped: AsyncTransactionalPersistencePortForTestOnly = { concurrencyIdentity: port.concurrencyIdentity, recover: port.recover.bind(port), commit: port.commit.bind(port), close: port.close.bind(port), recoverOperationBinding: async (operationId) => operationId === id(10) ? projection === undefined ? undefined : { commitId: id(10), operationBindingSha256: projection } : port.recoverOperationBinding(operationId) }; await expect(new AsyncTransactionalCapabilityJournal(wrapped, provider, () => { refs += 1; return id(900 + refs); }).issue({ spaceId: id(3), keyId: id(20), bundle: start })).rejects.toBeInstanceOf(AsyncTransactionalCapabilityJournalError); expect([providers, refs, await generation(port)]).toEqual([0, 0, 1]); }
    expect(expected).toMatch(/^[a-f0-9]{64}$/u); await port.close();
  });

  it("bounds hostile enumerable extras and never invokes an own ArrayBuffer byteLength accessor", async () => {
    const root = await fixture(); const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); let providers = 0; let refs = 0; const provider: WorkspaceKeyProvider = { async withUnlockedKey(_reference, callback) { providers += 1; await callback(new Uint8Array(32).fill(7)); } }; const set = new AsyncTransactionalEncryptedWorkSet(port, provider, () => { refs += 1; return id(950 + refs); }); const base = input(id(61)); const extra = [...base.writes]; Object.defineProperty(extra, "extra", { enumerable: true, value: 1 }); const huge = { ...base } as Record<string, unknown>; for (let index = 0; index < 10_000; index += 1) Object.defineProperty(huge, `extra${index}`, { enumerable: true, value: index }); const bytes = new Uint8Array([1, 2, 3]); let invoked = false; Object.defineProperty(bytes.buffer, "byteLength", { configurable: true, get() { invoked = true; throw new Error("must not run"); } });
    for (const hostile of [{ ...base, writes: extra }, huge]) await expect(set.putAtomic(hostile as never)).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); await expect(set.putAtomic({ ...base, writes: [{ ...base.writes[0]!, plaintext: bytes }] })).resolves.toHaveLength(1); expect([providers, refs, invoked, await generation(port)]).toEqual([2, 1, false, 1]); await port.close();
  });

  it("retries one injected prepublication interruption with the retained request and accepts lost acknowledgement exact reconciliation", async () => {
    const root = await fixture(); const filesystem = new TransactionalPersistenceFilesystemForTestOnly(root); const raw = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); let interrupted = true;
    const pre: AsyncTransactionalPersistencePortForTestOnly = { concurrencyIdentity: raw.concurrencyIdentity, recover: raw.recover.bind(raw), recoverOperationBinding: raw.recoverOperationBinding.bind(raw), commit: async (request) => { if (interrupted) { interrupted = false; throw new TransactionalPersistenceError("INTERRUPTED"); } return raw.commit(request); }, close: raw.close.bind(raw) };
    await expect(journal(pre).issue({ spaceId: id(3), keyId: id(20), bundle: issued() })).resolves.toHaveLength(4); expect(await generation(raw)).toBe(1); await raw.close();
    let acknowledged = false; const lost = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root, () => ({ loadLatest: () => filesystem.loadLatest(), publish: async (image) => { const result = await filesystem.publish(image); if (!acknowledged) { acknowledged = true; throw new Error("lost"); } return result; } }));
    await expect(new AsyncTransactionalEncryptedWorkSet(lost, keyProvider(), () => id(601)).putAtomic(input(id(54)))).resolves.toHaveLength(1); expect(await generation(lost)).toBe(2); await lost.close();
  });

  it("maps unavailable reconcile and another valid winner to one fixed A4 error without rebasing", async () => {
    const root = await fixture(); const fs = new TransactionalPersistenceFilesystemForTestOnly(root); let offline = false; let publications = 0;
    const unavailable = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root, () => ({ loadLatest: async () => { if (offline) throw new Error("offline"); return fs.loadLatest(); }, publish: async (image) => { publications += 1; if (publications === 1) return fs.publish(image); offline = true; throw new Error("pre"); } }));
    const failure = await new AsyncTransactionalEncryptedWorkSet(unavailable, keyProvider()).putAtomic(input(id(55))).catch((error: unknown) => error); expect(failure).toMatchObject({ code: "ASYNC_TRANSACTIONAL_ENCRYPTED_WORK_SET_FAILED", message: "Async transactional encrypted work set operation failed." }); expect((failure as Error).message).not.toContain(root.path); await unavailable.close();
    let competingPublications = 1; const competing = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root, () => ({ loadLatest: () => fs.loadLatest(), publish: async (candidate) => { competingPublications += 1; if (competingPublications === 1) return fs.publish(candidate); let latest: TransactionalPersistenceMediumImage | undefined; let medium: InMemoryTransactionalPersistenceMedium | undefined; let image: TransactionalPersistenceMediumImage | undefined; let state: RecoveredTransactionalState | undefined; try { latest = await fs.loadLatest(); if (latest === undefined) throw new Error("missing genesis"); medium = InMemoryTransactionalPersistenceMedium.fromImageForTestOnly(latest); state = medium.openPortForTestOnly().recover(); medium.openPortForTestOnly().commit({ commitId: id(56), expectedGeneration: state.generation, expectedSnapshotSha256: state.snapshotSha256, operationBindingSha256: "b".repeat(64), snapshot: (candidate as TransactionalPersistenceMediumImage).state.snapshot }); image = medium.exportImageForTestOnly(); await fs.publish(image); } finally { medium?.disposeForTestOnly(); disposeOpaqueJournalSnapshotForTestOnly(latest?.state.snapshot); disposeOpaqueJournalSnapshotForTestOnly(state?.snapshot); if (image !== undefined) disposeTransactionalPersistenceMediumImageForTestOnly(image); } throw new Error("other valid winner"); } }));
    await expect(new AsyncTransactionalEncryptedWorkSet(competing, keyProvider()).putAtomic(input(id(57)))).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); expect(await generation(competing)).toBe(1); expect(await competing.recoverOperationBinding(id(56))).toMatchObject({ commitId: id(56) }); await competing.close();
  });

  it("admits one divergent same-root terminal winner and keeps the other from rebasing", async () => {
    const root = await fixture(); const left = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const right = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const start = issued(); await journal(left).issue({ spaceId: id(3), keyId: id(20), bundle: start }); const consumed = terminal(); const revoked = prepareTerminalCapabilityJournal({ predecessor: { state: start.state, receipt: start.receipt }, lifecycle: "revoked", lifecycleId: id(112), operationId: id(113), receiptId: id(114), recordedAt: "2026-08-03T00:04:59.999Z" });
    const outcomes = await Promise.allSettled([journal(left, 800).terminalize({ spaceId: id(3), keyId: id(20), bundle: consumed }), journal(right, 900).terminalize({ spaceId: id(3), keyId: id(20), bundle: revoked })]); expect(outcomes.filter((outcome) => outcome.status === "fulfilled")).toHaveLength(1); expect(await generation(left)).toBe(2); await left.close(); await right.close();
  });

  it("closes a port after its accepted blocked operation, leaving queued work before provider entry and no partial disk state", async () => {
    const root = await fixture(); const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); const gate = deferred<void>(); const entered = deferred<void>(); let calls = 0; const provider: WorkspaceKeyProvider = { async withUnlockedKey(_reference, callback) { calls += 1; entered.resolve(); await gate.promise; const key = new Uint8Array(32).fill(7); try { await callback(key); } finally { key.fill(0); } } }; const first = new AsyncTransactionalEncryptedWorkSet(port, provider, () => id(1000)); const second = new AsyncTransactionalEncryptedWorkSet(port, provider, () => id(1100));
    const running = first.putAtomic(input(id(58))); await entered.promise; const queued = second.putAtomic(input(id(59))); const closing = port.close(); gate.resolve(); await expect(running).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); await expect(queued).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); await closing; expect(calls).toBe(1);
    const reopened = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); expect(await generation(reopened)).toBe(0); await reopened.close();
  });

  it("rejects hostile data before provider or disk and keeps private gates false", async () => {
    const root = await fixture(); const port = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); let calls = 0; const provider = keyProvider({ get calls() { return calls; } }); const counting: WorkspaceKeyProvider = { async withUnlockedKey(reference, callback) { calls += 1; await provider.withUnlockedKey(reference, callback); } }; const set = new AsyncTransactionalEncryptedWorkSet(port, counting);
    const base = input(id(60)); const accessor = { ...base }; Object.defineProperty(accessor, "writes", { enumerable: true, get: () => [base.writes[0]] }); const sparse: unknown[] = []; sparse.length = 1; const subview = new Uint8Array(new Uint8Array([1, 2]).buffer, 1); const shared = new Uint8Array(new SharedArrayBuffer(1)); const bad = [new Proxy(base, {}), accessor, { ...base, writes: sparse }, { ...base, writes: [{ ...base.writes[0]!, plaintext: subview }] }, { ...base, writes: [{ ...base.writes[0]!, plaintext: shared }] }];
    for (const value of bad) await expect(set.putAtomic(value as never)).rejects.toBeInstanceOf(AsyncTransactionalEncryptedWorkSetError); expect(calls).toBe(0); expect(await generation(port)).toBe(0); await port.close();
    const source = `${readFileSync(new URL("./async-transactional-encrypted-work-set.ts", import.meta.url), "utf8")}\n${readFileSync(new URL("./async-transactional-capability-journal.ts", import.meta.url), "utf8")}`; const barrel = readFileSync(new URL("../index.ts", import.meta.url), "utf8"); const packageManifest = readFileSync(new URL("../../package.json", import.meta.url), "utf8"); const daemon = readFileSync(new URL("../../../../apps/daemon/src/index.ts", import.meta.url), "utf8"); const contracts = readFileSync(new URL("../../../contracts/src/index.ts", import.meta.url), "utf8"); const gate = readFileSync(new URL("../../../../apps/desktop/src/main/durable-spaces-gate.ts", import.meta.url), "utf8"); const packageGate = readFileSync(new URL("../../../../apps/desktop/scripts/inspect-storage-capability-package.mjs", import.meta.url), "utf8");
    expect(source).not.toMatch(/node:(?:fs|path|http|https|child_process)|electron|\bipc\b|process\.env|\bfetch\b|effect execution/i); for (const surface of [barrel, packageManifest, daemon, contracts]) expect(surface).not.toMatch(/async-transactional-(?:capability-journal|encrypted-work-set)/); expect(gate).toMatch(/DURABLE_SPACES_ENABLED\s*=\s*false/); expect(packageGate).toMatch(/durableSpacesEnabled:\s*false/);
  });

  it("maps actual wrong-mode and corrupt newest generations to the fixed journal error", async () => {
    const root = await fixture(); const first = await AsyncTransactionalPersistenceFilesystemPortForTestOnly.open(root); await journal(first).issue({ spaceId: id(3), keyId: id(20), bundle: issued() });
    const newest = join(root.path, "generation-00000000000000000001"); await chmod(newest, 0o644); const wrongMode = await journal(first).issue({ spaceId: id(3), keyId: id(20), bundle: issued() }).catch((error: unknown) => error); expect(wrongMode).toMatchObject({ code: "ASYNC_TRANSACTIONAL_CAPABILITY_JOURNAL_FAILED", message: "Async transactional capability journal operation failed." }); expect((wrongMode as Error).message).not.toContain(root.path); expect((wrongMode as { cause?: unknown }).cause).toBeUndefined();
    await chmod(newest, 0o600); await writeFile(newest, new Uint8Array([1, 2, 3]), { mode: 0o600 }); const corrupt = await journal(first).issue({ spaceId: id(3), keyId: id(20), bundle: issued() }).catch((error: unknown) => error); expect(corrupt).toMatchObject({ code: "ASYNC_TRANSACTIONAL_CAPABILITY_JOURNAL_FAILED", message: "Async transactional capability journal operation failed." }); expect((corrupt as Error).message).not.toContain(root.path); expect((corrupt as { cause?: unknown }).cause).toBeUndefined(); await first.close();
  });
});
