import { types } from "node:util";
import { CanonicalDurableIdSchema } from "@cadrane/contracts";
import { DurableJournalIdempotencySchema, type DurableJournalIdempotency, type DurableJournalRecord } from "@cadrane/contracts/durable-journal";
import { AsyncTransactionalEncryptedWorkSet } from "./async-transactional-encrypted-work-set.js";
import { type AsyncTransactionalPersistencePortForTestOnly } from "./async-transactional-persistence-filesystem-port.js";
import { EncryptedWorkStore, type EncryptedWorkStorePutInput, type WorkspaceKeyProvider } from "./encrypted-work-store.js";
import { InMemoryWorkStore } from "./in-memory-work-store.js";
import { enqueueTransactionalPortOperation } from "./transactional-port-queue.js";
import { disposeOpaqueJournalSnapshotForTestOnly, restoreInMemoryWorkStoreFromSnapshotForTestOnly, validateRecoveredTransactionalStateForTestOnly, type RecoveredTransactionalState } from "./transactional-persistence.js";

const MAX = 8 * 1024 * 1024; const KINDS = new Set<EncryptedWorkStorePutInput["entityKind"]>(["space", "source", "source-snapshot", "source-span", "agent", "agent-version", "task", "run", "run-step", "artifact", "review", "revision-request", "permission-request", "permission-decision", "citation", "receipt", "capability-grant", "capability-grant-receipt", "capability-grant-index"]);
const TYPED = Object.getPrototypeOf(Uint8Array.prototype); const LENGTH = Object.getOwnPropertyDescriptor(TYPED, "byteLength")?.get; const BUFFER = Object.getOwnPropertyDescriptor(TYPED, "buffer")?.get; const OFFSET = Object.getOwnPropertyDescriptor(TYPED, "byteOffset")?.get; const ARRAY_LENGTH = Object.getOwnPropertyDescriptor(ArrayBuffer.prototype, "byteLength")?.get; const SHARED = typeof SharedArrayBuffer === "undefined" ? undefined : Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength")?.get;
export interface AsyncTransactionalEncryptedWorkStorePutInput { readonly operationId: string; readonly spaceId: string; readonly keyId: string; readonly id: string; readonly entityKind: EncryptedWorkStorePutInput["entityKind"]; readonly recordRevision: number; readonly idempotency: DurableJournalIdempotency; readonly kind: "payload" | "blob"; readonly plaintext: Uint8Array; }
export interface AsyncTransactionalEncryptedWorkStoreReadInput { readonly spaceId: string; readonly keyId: string; readonly id: string; readonly recordRevision: number; }
export class AsyncTransactionalEncryptedWorkStoreError extends Error { readonly code = "ASYNC_TRANSACTIONAL_ENCRYPTED_WORK_STORE_FAILED" as const; constructor() { super("Async transactional encrypted work store operation failed."); this.name = "AsyncTransactionalEncryptedWorkStoreError"; } }

/** Private async facade; it borrows the A3 port and delegates writes to A4. */
export class AsyncTransactionalEncryptedWorkStore {
  private readonly identity: object; private readonly writes: AsyncTransactionalEncryptedWorkSet;
  constructor(private readonly port: AsyncTransactionalPersistencePortForTestOnly, private readonly provider: WorkspaceKeyProvider, refs?: () => string) { try { const identity = port.concurrencyIdentity; if (identity === null || typeof identity !== "object" || types.isProxy(identity)) throw failed(); this.identity = identity; this.writes = new AsyncTransactionalEncryptedWorkSet(port, provider, refs); } catch (_error) { throw failed(); } }
  async put(input: AsyncTransactionalEncryptedWorkStorePutInput): Promise<DurableJournalRecord> { let owned: OwnedPut | undefined; try { owned = parsePut(input); } catch (_error) { throw failed(); } try { const records = await this.writes.putAtomic({ operationId: owned.operationId, spaceId: owned.spaceId, keyId: owned.keyId, writes: [toWrite(owned)] }); if (records.length !== 1) throw failed(); return frozen(records[0]!); } catch (_error) { throw failed(); } finally { owned?.plaintext.fill(0); } }
  async read(input: AsyncTransactionalEncryptedWorkStoreReadInput): Promise<Uint8Array> { let owned: OwnedRead | undefined; let recovered: RecoveredTransactionalState | undefined; let validated: RecoveredTransactionalState | undefined; let store: InMemoryWorkStore | undefined; let output: Uint8Array | undefined; try { owned = parseRead(input); return await enqueueTransactionalPortOperation(this.identity, async () => { recovered = await this.port.recover(); validated = validateRecoveredTransactionalStateForTestOnly(recovered); store = restoreInMemoryWorkStoreFromSnapshotForTestOnly(validated.snapshot); const plaintext = await new EncryptedWorkStore(store, this.provider).read(owned!); try { output = new Uint8Array(plaintext); return output; } finally { plaintext.fill(0); } }); } catch (_error) { output?.fill(0); throw failed(); } finally { store?.disposeForTestOnly(); disposeOpaqueJournalSnapshotForTestOnly(validated?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(recovered?.snapshot); } }
}
interface OwnedPut { readonly operationId: string; readonly spaceId: string; readonly keyId: string; readonly id: string; readonly entityKind: EncryptedWorkStorePutInput["entityKind"]; readonly recordRevision: number; readonly idempotency: DurableJournalIdempotency; readonly kind: "payload" | "blob"; readonly plaintext: Uint8Array; }
interface OwnedRead { readonly spaceId: string; readonly keyId: string; readonly id: string; readonly recordRevision: number; }
function parsePut(value: unknown): OwnedPut { const raw = exact(value, ["operationId", "spaceId", "keyId", "id", "entityKind", "recordRevision", "idempotency", "kind", "plaintext"]); if (raw === undefined || !id(raw.operationId) || !id(raw.spaceId) || !id(raw.keyId) || !id(raw.id) || !KINDS.has(raw.entityKind as EncryptedWorkStorePutInput["entityKind"]) || !Number.isSafeInteger(raw.recordRevision) || (raw.recordRevision as number) < 1 || (raw.kind !== "payload" && raw.kind !== "blob")) throw failed(); const idem = DurableJournalIdempotencySchema.safeParse(copyIdempotency(raw.idempotency)); const length = bytesLength(raw.plaintext); if (!idem.success) throw failed(); let plaintext: Uint8Array | undefined; try { plaintext = new Uint8Array(raw.plaintext as Uint8Array); if (plaintext.byteLength !== length) throw failed(); return Object.freeze({ operationId: raw.operationId as string, spaceId: raw.spaceId as string, keyId: raw.keyId as string, id: raw.id as string, entityKind: raw.entityKind as EncryptedWorkStorePutInput["entityKind"], recordRevision: raw.recordRevision as number, idempotency: idem.data, kind: raw.kind as "payload" | "blob", plaintext }); } catch (_error) { plaintext?.fill(0); throw failed(); } }
function parseRead(value: unknown): OwnedRead { const raw = exact(value, ["spaceId", "keyId", "id", "recordRevision"]); if (raw === undefined || !id(raw.spaceId) || !id(raw.keyId) || !id(raw.id) || !Number.isSafeInteger(raw.recordRevision) || (raw.recordRevision as number) < 1) throw failed(); return Object.freeze({ spaceId: raw.spaceId as string, keyId: raw.keyId as string, id: raw.id as string, recordRevision: raw.recordRevision as number }); }
function exact(value: unknown, fields: readonly string[]): Record<string, unknown> | undefined { try { if (value === null || typeof value !== "object" || types.isProxy(value) || Object.getPrototypeOf(value) !== Object.prototype) return undefined; let count = 0; for (const key in value) { if (!Object.hasOwn(value, key) || !fields.includes(key) || ++count > fields.length) return undefined; } if (count !== fields.length) return undefined; const out: Record<string, unknown> = {}; for (const key of fields) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor)) return undefined; out[key] = descriptor.value; } return out; } catch (_error) { return undefined; } }
function copyIdempotency(value: unknown): Record<string, unknown> | undefined { const raw = exactLoose(value, 3); if (raw === undefined) return undefined; const kind = raw.kind; const fields = kind === "entity" ? ["kind"] : kind === "task" ? ["kind", "idempotencyKeySha256"] : kind === "run" ? ["kind", "taskId", "attempt"] : kind === "revision" ? ["kind", "reviewId", "requestSha256"] : kind === "receipt" ? ["kind", "runId"] : undefined; return fields === undefined ? undefined : exact(raw, fields); }
function exactLoose(value: unknown, maximum: number): Record<string, unknown> | undefined { try { if (value === null || typeof value !== "object" || types.isProxy(value) || Object.getPrototypeOf(value) !== Object.prototype) return undefined; const out: Record<string, unknown> = {}; let count = 0; for (const key in value) { if (!Object.hasOwn(value, key) || ++count > maximum) return undefined; const descriptor = Object.getOwnPropertyDescriptor(value, key); if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor)) return undefined; out[key] = descriptor.value; } return out; } catch (_error) { return undefined; } }
function bytesLength(value: unknown): number { if (types.isProxy(value) || !(value instanceof Uint8Array) || Object.getPrototypeOf(value) !== Uint8Array.prototype || LENGTH === undefined || BUFFER === undefined || OFFSET === undefined || ARRAY_LENGTH === undefined || Object.hasOwn(value, "byteLength") || Object.hasOwn(value, "buffer") || Object.hasOwn(value, "byteOffset") || Object.hasOwn(value, "length")) throw failed(); const length = LENGTH.call(value); const buffer = BUFFER.call(value); if (types.isProxy(buffer) || OFFSET.call(value) !== 0 || !Number.isSafeInteger(length) || length < 0 || length > MAX || ARRAY_LENGTH.call(buffer) !== length || (SHARED !== undefined && (() => { try { return typeof SHARED.call(buffer) === "number"; } catch { return false; } })())) throw failed(); return length; }
function toWrite(value: OwnedPut) { return { id: value.id, entityKind: value.entityKind, recordRevision: value.recordRevision, idempotency: value.idempotency, kind: value.kind, plaintext: value.plaintext }; }
function id(value: unknown): value is string { return CanonicalDurableIdSchema.safeParse(value).success; }
function frozen(record: DurableJournalRecord): DurableJournalRecord { return deepFreeze(JSON.parse(JSON.stringify(record)) as DurableJournalRecord); }
function deepFreeze<T>(value: T): T { if (value !== null && typeof value === "object") { for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); Object.freeze(value); } return value; }
function failed(): AsyncTransactionalEncryptedWorkStoreError { return new AsyncTransactionalEncryptedWorkStoreError(); }
