import { describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { canonicalCapabilityIntentSha256 } from "../capability-intent-binding.js";
import { prepareIssuedCapabilityJournal, prepareTerminalCapabilityJournal } from "../capability-journal-codec.js";
import { disposeEncodedCapabilityJournalStorageBundle, encodeCapabilityJournalStorageBundle } from "../capability-journal-storage-codec.js";
import { type WorkspaceKeyProvider } from "./encrypted-work-store.js";
import { InMemoryWorkStore } from "./in-memory-work-store.js";
import { TransactionalEncryptedWorkStore } from "./transactional-encrypted-work-store.js";
import { InMemoryTransactionalPersistenceMedium, snapshotFromInMemoryWorkStoreForTestOnly } from "./transactional-persistence.js";
import { TransactionalCapabilityJournal, TransactionalCapabilityJournalError } from "./transactional-capability-journal.js";
import { TransactionalEncryptedWorkSet, TransactionalEncryptedWorkSetError } from "./transactional-encrypted-work-set.js";

const id=(value:number)=>`00000000-0000-4000-8000-${value.toString().padStart(12,"0")}`;
const hash="a".repeat(64);
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const provider:WorkspaceKeyProvider={async withUnlockedKey(_ref,callback){await callback(new Uint8Array(32).fill(3));}};
function issued(seed=0, ids?:{requestId?:string;decisionId?:string;spaceId?:string;issueOperationId?:string}){const keyed=(value:number)=>id(value+seed);const requestId=ids?.requestId??keyed(1);const decisionId=ids?.decisionId??keyed(2);const spaceId=ids?.spaceId??keyed(3);const intent={schemaVersion:1,permissionRequestId:requestId,permissionDecisionId:decisionId,spaceId,runId:keyed(4),effectId:keyed(5),effectRevision:1,effectKind:"export-artifact",authoritySessionId:keyed(6),subjectBindingSha256:hash,targetBindingSha256:hash,parameterSha256:hash,requestSha256:hash,expiresAt:"2026-08-03T00:05:00.000Z",maxUses:1} as const;return prepareIssuedCapabilityJournal({grantRecordId:keyed(15),grantId:keyed(7),intent,approvalEvidence:{schemaVersion:1,kind:"capability-approval-evidence",verifierId:keyed(8),verdict:"approved",permissionRequestId:requestId,permissionDecisionId:decisionId,authoritySessionId:keyed(6),requestSha256:hash,intentSha256:canonicalCapabilityIntentSha256(intent),expiresAt:intent.expiresAt},issuedAt:"2026-08-03T00:00:00.000Z",issueLifecycleId:keyed(9),issueOperationId:ids?.issueOperationId??keyed(10),issueReceiptId:keyed(11)});}
function terminal(lifecycle:"consumed"|"revoked"="consumed"){const prior=issued();return prepareTerminalCapabilityJournal({predecessor:{state:prior.state,receipt:prior.receipt},lifecycle,lifecycleId:id(12),operationId:id(13),receiptId:id(14),recordedAt:"2026-08-03T00:04:59.999Z"});}
function journal(medium:InMemoryTransactionalPersistenceMedium,firstRef=1000){let ref=firstRef;return new TransactionalCapabilityJournal(medium.openPortForTestOnly(),provider,()=>id(ref++));}
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>((done)=>{resolve=done;});return{promise,resolve};}
function transcriptStore(){let event=8091;const store=new InMemoryWorkStore(()=>id(8090),()=>id(event++));const add=(entityId:string,kind:"task"|"run",bytes:string)=>store.putRecord({ciphertext:new Uint8Array(Buffer.from(bytes)),record:{schemaVersion:1,id:entityId,spaceId:id(3),recordRevision:1,idempotency:kind==="task"?{kind,idempotencyKeySha256:sha("task")}:{kind,taskId:id(8010),attempt:1},envelope:{envelopeVersion:1,spaceId:id(3),keyId:id(20),entityId,entityKind:kind,schemaVersion:1,contentRevision:1,kind:"payload",contentSha256:sha(bytes),nonce:"AAAAAAAAAAAAAAAA",ciphertextRef:id(kind==="task"?8092:8093),ciphertextSha256:sha(bytes),tag:"AAAAAAAAAAAAAAAAAAAAAA"}}} as never);add(id(8010),"task","task");add(id(8011),"run","run");store.appendEvent({schemaVersion:1,id:id(8094),spaceId:id(3),runId:id(8011),runRevision:1,sequence:1,kind:"run-recorded",runCiphertextSha256:sha("run"),effectId:null,effectRevision:null,effectState:null,claimSha256:null});const effect=store.putEffect({schemaVersion:1,id:id(8095),spaceId:id(3),runId:id(8011),runRevision:1,stepKey:id(8096),requestSha256:sha("effect"),state:"pending",effectRevision:1,claimId:null});store.claimEffect(id(3),effect.id,1);return store;}

describe("private transactional capability journal",()=>{
  it("requires a fully persisted, ordered, byte-exact prerequisite set before one conditional generation",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();let ref=900;const set=new TransactionalEncryptedWorkSet(medium.openPortForTestOnly(),provider,()=>id(ref++));const prerequisite={id:id(30),entityKind:"capability-grant" as const,recordRevision:1,idempotency:{kind:"entity" as const},kind:"payload" as const,plaintext:new Uint8Array(Buffer.from("issued"))};await set.putAtomic({operationId:id(31),spaceId:id(3),keyId:id(20),writes:[prerequisite]});const target={...prerequisite,recordRevision:2,plaintext:new Uint8Array(Buffer.from("terminal"))};await expect(set.putAtomicAfterExactPrerequisite({operationId:id(32),prerequisiteOperationId:id(31),spaceId:id(3),keyId:id(20),prerequisites:[{...prerequisite,plaintext:new Uint8Array(Buffer.from("issued"))}],writes:[target]})).resolves.toHaveLength(1);expect(medium.openPortForTestOnly().recover().generation).toBe(2);await expect(set.putAtomicAfterExactPrerequisite({operationId:id(33),prerequisiteOperationId:id(31),spaceId:id(3),keyId:id(20),prerequisites:[{...prerequisite,plaintext:new Uint8Array(Buffer.from("forged"))}],writes:[{...target,id:id(34),recordRevision:1,plaintext:new Uint8Array(Buffer.from("other"))}]})).rejects.toBeInstanceOf(TransactionalEncryptedWorkSetError);expect(medium.openPortForTestOnly().recover().generation).toBe(2);});
  it("issues and terminalizes the exact canonical records in fixed order",async()=>{
    const medium=new InMemoryTransactionalPersistenceMedium();const start=issued();const end=terminal();const service=journal(medium);
    const encodedStart=encodeCapabilityJournalStorageBundle(start);const encodedEnd=encodeCapabilityJournalStorageBundle(end);
    try{
      const first=await service.issue({spaceId:id(3),keyId:id(20),bundle:start});
      expect(first.map((record)=>[record.id,record.envelope.entityKind,record.recordRevision])).toEqual(
        [encodedStart.state,encodedStart.receipt,...encodedStart.indexes].map((record)=>[record.id,record.entityKind,record.recordRevision])
      );
      expect(medium.openPortForTestOnly().recover().generation).toBe(1);
      expect(await service.issue({spaceId:id(3),keyId:id(20),bundle:start})).toEqual(first);
      const last=await service.terminalize({spaceId:id(3),keyId:id(20),bundle:end});
      expect(last.map((record)=>[record.id,record.envelope.entityKind,record.recordRevision])).toEqual(
        [encodedEnd.state,encodedEnd.receipt,...encodedEnd.indexes].map((record)=>[record.id,record.entityKind,record.recordRevision])
      );
      expect(medium.openPortForTestOnly().recover().generation).toBe(2);
      expect(await service.terminalize({spaceId:id(3),keyId:id(20),bundle:end})).toEqual(last);
      for(const record of last)expect(Object.isFrozen(record)).toBe(true);
    }finally{disposeEncodedCapabilityJournalStorageBundle(encodedStart);disposeEncodedCapabilityJournalStorageBundle(encodedEnd);}
  });
  it("retries interrupted issue and terminal commits without partial journals",async()=>{for(const point of ["before-publish","after-staging-bytes","after-staging-metadata","after-publish-before-ack"] as const){const medium=new InMemoryTransactionalPersistenceMedium();medium.setFaultForTestOnly(point);const service=journal(medium);await service.issue({spaceId:id(3),keyId:id(20),bundle:issued()});expect(medium.openPortForTestOnly().recover().snapshot.journal.records).toHaveLength(4);medium.setFaultForTestOnly(point);await service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()});expect(medium.openPortForTestOnly().recover().snapshot.journal.records).toHaveLength(6);}});
  it("rejects missing, wrong, reordered, and cross-space predecessor inputs with one generic error",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);const end=terminal();await expect(service.terminalize({spaceId:id(3),keyId:id(20),bundle:end})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);await service.issue({spaceId:id(3),keyId:id(20),bundle:issued()});const wrong=terminal("revoked");await expect(service.terminalize({spaceId:id(3),keyId:id(20),bundle:{...wrong,predecessor:{state:wrong.predecessor!.state,receipt:issued(100).receipt}}})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);await expect(service.terminalize({spaceId:id(103),keyId:id(20),bundle:end})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);expect(medium.openPortForTestOnly().recover().generation).toBe(1);});
  it("serializes competing terminal transitions to a single winner",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);await service.issue({spaceId:id(3),keyId:id(20),bundle:issued()});const [a,b]=await Promise.allSettled([service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal("consumed")}),service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal("revoked")})]);expect([a,b].filter((result)=>result.status==="fulfilled")).toHaveLength(1);expect(medium.openPortForTestOnly().recover().generation).toBe(2);});
  it("makes exact concurrent issue calls one generation and replays from a recovered image",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();const start=issued();const service=journal(medium);const results=await Promise.all([service.issue({spaceId:id(3),keyId:id(20),bundle:start}),service.issue({spaceId:id(3),keyId:id(20),bundle:start})]);expect(results[0]).toEqual(results[1]);expect(medium.openPortForTestOnly().recover().generation).toBe(1);const recovered=InMemoryTransactionalPersistenceMedium.fromImageForTestOnly(medium.exportImageForTestOnly());await expect(journal(recovered).issue({spaceId:id(3),keyId:id(20),bundle:start})).resolves.toHaveLength(4);expect(recovered.openPortForTestOnly().recover().generation).toBe(1);});
  it("keeps the unsupported old-image rollback branch explicit",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);const start=issued();await service.issue({spaceId:id(3),keyId:id(20),bundle:start});const image=medium.exportImageForTestOnly();await service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal("consumed")});const restored=InMemoryTransactionalPersistenceMedium.fromImageForTestOnly(image);await expect(journal(restored,2000).terminalize({spaceId:id(3),keyId:id(20),bundle:terminal("revoked")})).resolves.toHaveLength(2);expect(restored.openPortForTestOnly().recover().generation).toBe(2);});
  it("rejects same request or decision conflicts in one Space, but permits their same pair in another Space",async()=>{const first=issued();const requestCollision=issued(100,{requestId:first.state.intent.permissionRequestId,spaceId:id(3)});const decisionCollision=issued(200,{decisionId:first.state.intent.permissionDecisionId,spaceId:id(3)});for(const collision of [requestCollision,decisionCollision]){const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);await service.issue({spaceId:id(3),keyId:id(20),bundle:first});await expect(service.issue({spaceId:id(3),keyId:id(20),bundle:collision})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);expect(medium.openPortForTestOnly().recover().generation).toBe(1);}const other=issued(300,{requestId:first.state.intent.permissionRequestId,decisionId:first.state.intent.permissionDecisionId,spaceId:id(303)});const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);const a=await service.issue({spaceId:id(3),keyId:id(20),bundle:first});const b=await service.issue({spaceId:id(303),keyId:id(20),bundle:other});expect(a.slice(2).map((record)=>record.id)).not.toEqual(b.slice(2).map((record)=>record.id));await expect(service.issue({spaceId:id(999),keyId:id(20),bundle:first})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);await expect(service.terminalize({spaceId:id(3),keyId:id(999),bundle:terminal()})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);});
  it("allows one conflicting issue winner while exact same issue concurrency remains idempotent",async()=>{const first=issued();const conflict=issued(100,{requestId:first.state.intent.permissionRequestId,spaceId:id(3)});const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);const outcomes=await Promise.allSettled([service.issue({spaceId:id(3),keyId:id(20),bundle:first}),service.issue({spaceId:id(3),keyId:id(20),bundle:conflict})]);expect(outcomes.filter((outcome)=>outcome.status==="fulfilled")).toHaveLength(1);expect(medium.openPortForTestOnly().recover().generation).toBe(1);});
  it("rejects a terminal when any persisted issuance record has foreign canonical bytes",async()=>{for(const replaced of [0,1,2,3]){const target=issued();const foreign=issued(100);const expected=encodeCapabilityJournalStorageBundle(target);const wrong=encodeCapabilityJournalStorageBundle(foreign);const records=[expected.state,expected.receipt,...expected.indexes];const foreignRecords=[wrong.state,wrong.receipt,...wrong.indexes];const medium=new InMemoryTransactionalPersistenceMedium();let ref=4000;const set=new TransactionalEncryptedWorkSet(medium.openPortForTestOnly(),provider,()=>id(ref++));try{await set.putAtomic({operationId:target.state.issueOperationId,spaceId:id(3),keyId:id(20),writes:records.map((record,index)=>({id:record.id,entityKind:record.entityKind,recordRevision:record.recordRevision,idempotency:{kind:"entity" as const},kind:"payload" as const,plaintext:new Uint8Array((index===replaced?foreignRecords[index]!:record).plaintext)}))});await expect(journal(medium,5000).terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);expect(medium.openPortForTestOnly().recover().generation).toBe(1);}finally{disposeEncodedCapabilityJournalStorageBundle(expected);disposeEncodedCapabilityJournalStorageBundle(wrong);}}});
  it("rejects reused issue and terminal operation IDs when the valid bundle changes",async()=>{const first=issued();const changed=issued(100,{issueOperationId:first.state.issueOperationId});const medium=new InMemoryTransactionalPersistenceMedium();const service=journal(medium);await service.issue({spaceId:id(3),keyId:id(20),bundle:first});await expect(service.issue({spaceId:id(103),keyId:id(20),bundle:changed})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);const end=terminal("consumed");await service.terminalize({spaceId:id(3),keyId:id(20),bundle:end});const other=issued(100);await service.issue({spaceId:id(103),keyId:id(20),bundle:other});const reused=prepareTerminalCapabilityJournal({predecessor:{state:other.state,receipt:other.receipt},lifecycle:"revoked",lifecycleId:id(112),operationId:end.state.terminal!.operationId,receiptId:id(114),recordedAt:"2026-08-03T00:04:59.999Z"});await expect(service.terminalize({spaceId:id(103),keyId:id(20),bundle:reused})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);expect(medium.openPortForTestOnly().recover().generation).toBe(3);});
  it("rejects conditional missing, partial, reordered, forged, and invalid-revision prerequisites before provider entry",async()=>{const medium=new InMemoryTransactionalPersistenceMedium();let calls=0;const counting:WorkspaceKeyProvider={async withUnlockedKey(_ref,callback){calls+=1;await callback(new Uint8Array(32).fill(3));}};let ref=6000;const set=new TransactionalEncryptedWorkSet(medium.openPortForTestOnly(),counting,()=>id(ref++));const base=(value:number,revision=1)=>({id:id(value),entityKind:"capability-grant" as const,recordRevision:revision,idempotency:{kind:"entity" as const},kind:"payload" as const,plaintext:new Uint8Array(Buffer.from(`v-${value}-${revision}`))});const prerequisite=[base(30),base(31)];await set.putAtomic({operationId:id(32),spaceId:id(3),keyId:id(20),writes:prerequisite});const before=calls;const target=base(33);for(const bad of [[base(30)],[base(31),base(30)],[base(30),base(31),base(34)],[{...base(30),entityKind:"artifact" as const}, {...base(31),plaintext:new Uint8Array(Buffer.from("wrong"))}]] )await expect(set.putAtomicAfterExactPrerequisite({operationId:id(35),prerequisiteOperationId:id(32),spaceId:id(3),keyId:id(20),prerequisites:bad,writes:[target]})).rejects.toBeInstanceOf(TransactionalEncryptedWorkSetError);await expect(set.putAtomicAfterExactPrerequisite({operationId:id(32),prerequisiteOperationId:id(32),spaceId:id(3),keyId:id(20),prerequisites:prerequisite,writes:[target]})).rejects.toBeInstanceOf(TransactionalEncryptedWorkSetError);await expect(set.putAtomicAfterExactPrerequisite({operationId:id(36),prerequisiteOperationId:id(32),spaceId:id(3),keyId:id(20),prerequisites:prerequisite,writes:[base(30,1)]})).rejects.toBeInstanceOf(TransactionalEncryptedWorkSetError);expect(calls).toBe(before);expect(medium.openPortForTestOnly().recover().generation).toBe(1);const conditional={operationId:id(37),prerequisiteOperationId:id(32),spaceId:id(3),keyId:id(20),prerequisites:prerequisite.map((item)=>({...item,plaintext:new Uint8Array(item.plaintext)})),writes:[target]};await set.putAtomicAfterExactPrerequisite(conditional);expect(await set.putAtomicAfterExactPrerequisite({...conditional,prerequisites:prerequisite.map((item)=>({...item,plaintext:new Uint8Array(item.plaintext)})),writes:[{...target,plaintext:new Uint8Array(target.plaintext)}]})).toHaveLength(1);});
  it("contains provider failure for issue and terminal verification at their exact prestate",async()=>{const failing:WorkspaceKeyProvider={async withUnlockedKey(){throw new Error("provider");}};const issueMedium=new InMemoryTransactionalPersistenceMedium();const issueService=new TransactionalCapabilityJournal(issueMedium.openPortForTestOnly(),failing,()=>id(7000));await expect(issueService.issue({spaceId:id(3),keyId:id(20),bundle:issued()})).rejects.toMatchObject({code:"TRANSACTIONAL_CAPABILITY_JOURNAL_FAILED",message:"Transactional capability journal operation failed."});expect(issueMedium.openPortForTestOnly().recover().generation).toBe(0);const terminalMedium=new InMemoryTransactionalPersistenceMedium();const normal=journal(terminalMedium);await normal.issue({spaceId:id(3),keyId:id(20),bundle:issued()});const failingTerminal=new TransactionalCapabilityJournal(terminalMedium.openPortForTestOnly(),failing,()=>id(7001));await expect(failingTerminal.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()})).rejects.toMatchObject({code:"TRANSACTIONAL_CAPABILITY_JOURNAL_FAILED"});expect(terminalMedium.openPortForTestOnly().recover().generation).toBe(1);});

  it("fails closed when the issued-operation binding changes only after terminal publication",async()=>{
    for(const mode of ["missing","changed"] as const){
      const medium=new InMemoryTransactionalPersistenceMedium();const port=medium.openPortForTestOnly();const start=issued();const end=terminal();let issueRef=7100;
      await new TransactionalCapabilityJournal(port,provider,()=>id(issueRef++)).issue({spaceId:id(3),keyId:id(20),bundle:start});
      let published=false;let terminalRef=7200;
      const wrapped={
        concurrencyIdentity:port.concurrencyIdentity,
        recover:port.recover.bind(port),
        commit:(request:Parameters<typeof port.commit>[0])=>{const receipt=port.commit(request);published=true;return receipt;},
        recoverOperationBinding:(commitId:string)=>{
          const binding=port.recoverOperationBinding(commitId);
          if(!published||commitId!==start.state.issueOperationId)return binding;
          return mode==="missing"?undefined:{commitId,operationBindingSha256:"0".repeat(64)};
        }
      };
      const service=new TransactionalCapabilityJournal(wrapped,provider,()=>id(terminalRef++));
      await expect(service.terminalize({spaceId:id(3),keyId:id(20),bundle:end})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);
      expect(port.recover().generation).toBe(2);expect(port.recover().snapshot.journal.records).toHaveLength(6);
      await expect(service.terminalize({spaceId:id(3),keyId:id(20),bundle:end})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);
      expect(port.recover().generation).toBe(2);
    }
  });

  it("leaves the exact prestate when issue or terminal target refs collide during staging",async()=>{
    const issueMedium=new InMemoryTransactionalPersistenceMedium();
    const issueService=new TransactionalCapabilityJournal(issueMedium.openPortForTestOnly(),provider,()=>id(7300));
    await expect(issueService.issue({spaceId:id(3),keyId:id(20),bundle:issued()})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);
    expect(issueMedium.openPortForTestOnly().recover().generation).toBe(0);
    expect(issueMedium.openPortForTestOnly().recover().snapshot.journal.records).toHaveLength(0);

    const terminalMedium=new InMemoryTransactionalPersistenceMedium();await journal(terminalMedium,7400).issue({spaceId:id(3),keyId:id(20),bundle:issued()});
    const terminalService=new TransactionalCapabilityJournal(terminalMedium.openPortForTestOnly(),provider,()=>id(7500));
    await expect(terminalService.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()})).rejects.toBeInstanceOf(TransactionalCapabilityJournalError);
    expect(terminalMedium.openPortForTestOnly().recover().generation).toBe(1);
    expect(terminalMedium.openPortForTestOnly().recover().snapshot.journal.records).toHaveLength(4);
  });

  it("shares the whole-operation queue with generic writes and captures queued caller input",async()=>{
    const medium=new InMemoryTransactionalPersistenceMedium();const gate=deferred<void>();const begun=deferred<void>();let calls=0;let active=0;let max=0;
    const delayed:WorkspaceKeyProvider={async withUnlockedKey(_ref,callback){active+=1;max=Math.max(max,active);const call=++calls;try{await callback(new Uint8Array(32).fill(3));if(call===1){begun.resolve();await gate.promise;}}finally{active-=1;}}};
    const port=medium.openPortForTestOnly();const generic=new TransactionalEncryptedWorkStore(port,delayed,()=>id(7600));let issueRef=7700;
    const service=new TransactionalCapabilityJournal(port,delayed,()=>id(issueRef++));
    const genericRun=generic.put({operationId:id(7601),spaceId:id(3),keyId:id(20),id:id(7602),entityKind:"artifact",recordRevision:1,idempotency:{kind:"entity"},kind:"payload",plaintext:new Uint8Array(Buffer.from("ahead"))});
    await begun.promise;
    const original=issued();const mutableInput=JSON.parse(JSON.stringify({spaceId:id(3),keyId:id(20),bundle:original})) as {spaceId:string;keyId:string;bundle:{state:{intent:{spaceId:string}}}};
    const issueRun=service.issue(mutableInput);mutableInput.spaceId=id(999);mutableInput.bundle.state.intent.spaceId=id(999);
    await Promise.resolve();expect(calls).toBe(1);gate.resolve();const [,issuedRecords]=await Promise.all([genericRun,issueRun]);
    expect(max).toBe(1);expect(medium.openPortForTestOnly().recover().generation).toBe(2);
    await expect(journal(medium,7800).issue({spaceId:id(3),keyId:id(20),bundle:original})).resolves.toEqual(issuedRecords);
  });

  it("queues conditional terminalization behind a generic write and releases the queue after failure",async()=>{
    const medium=new InMemoryTransactionalPersistenceMedium();await journal(medium,7900).issue({spaceId:id(3),keyId:id(20),bundle:issued()});
    const port=medium.openPortForTestOnly();const gate=deferred<void>();const begun=deferred<void>();let calls=0;let active=0;let max=0;
    const delayed:WorkspaceKeyProvider={async withUnlockedKey(_ref,callback){active+=1;max=Math.max(max,active);const call=++calls;try{await callback(new Uint8Array(32).fill(3));if(call===1){begun.resolve();await gate.promise;}}finally{active-=1;}}};
    const generic=new TransactionalEncryptedWorkStore(port,delayed,()=>id(8000));let terminalRef=8100;const service=new TransactionalCapabilityJournal(port,delayed,()=>id(terminalRef++));
    const genericRun=generic.put({operationId:id(8001),spaceId:id(3),keyId:id(20),id:id(8002),entityKind:"artifact",recordRevision:1,idempotency:{kind:"entity"},kind:"payload",plaintext:new Uint8Array(Buffer.from("ahead-terminal"))});
    await begun.promise;const terminalRun=service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()});await Promise.resolve();expect(calls).toBe(1);gate.resolve();await Promise.all([genericRun,terminalRun]);
    expect(max).toBe(1);expect(port.recover().generation).toBe(3);

    const releaseMedium=new InMemoryTransactionalPersistenceMedium();await journal(releaseMedium,8200).issue({spaceId:id(3),keyId:id(20),bundle:issued()});const releasePort=releaseMedium.openPortForTestOnly();let reject=true;
    const flaky:WorkspaceKeyProvider={async withUnlockedKey(_ref,callback){if(reject){reject=false;throw new Error("provider");}await callback(new Uint8Array(32).fill(3));}};
    const failing=new TransactionalEncryptedWorkStore(releasePort,flaky,()=>id(8300));let releaseRef=8400;const released=new TransactionalCapabilityJournal(releasePort,flaky,()=>id(releaseRef++));
    const failedRun=failing.put({operationId:id(8301),spaceId:id(3),keyId:id(20),id:id(8302),entityKind:"artifact",recordRevision:1,idempotency:{kind:"entity"},kind:"payload",plaintext:new Uint8Array(Buffer.from("fail"))});
    const releasedRun=released.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()});const outcomes=await Promise.allSettled([failedRun,releasedRun]);
    expect(outcomes[0]?.status).toBe("rejected");expect(outcomes[1]?.status).toBe("fulfilled");expect(releasePort.recover().generation).toBe(2);
  });

  it("preserves a nonempty event, effect, and claim transcript through issue and terminal generations",async()=>{
    const medium=new InMemoryTransactionalPersistenceMedium();const port=medium.openPortForTestOnly();const empty=port.recover();const seed=transcriptStore();const snapshot=snapshotFromInMemoryWorkStoreForTestOnly(seed);seed.disposeForTestOnly();
    port.commit({commitId:id(8500),expectedGeneration:empty.generation,expectedSnapshotSha256:empty.snapshotSha256,operationBindingSha256:sha("transcript-seed"),snapshot});
    const before=port.recover().snapshot;const transcript=JSON.stringify({events:before.journal.events,effects:before.journal.effects,claims:before.issuedClaims});const service=journal(medium,8600);
    await service.issue({spaceId:id(3),keyId:id(20),bundle:issued()});await service.terminalize({spaceId:id(3),keyId:id(20),bundle:terminal()});
    const after=port.recover().snapshot;expect(JSON.stringify({events:after.journal.events,effects:after.journal.effects,claims:after.issuedClaims})).toBe(transcript);expect(port.recover().generation).toBe(3);
  });

  it("returns fixed errors for hostile inputs and deeply frozen metadata-only results",async()=>{const service=journal(new InMemoryTransactionalPersistenceMedium());const valid={spaceId:id(3),keyId:id(20),bundle:issued()};const accessor={...valid};Object.defineProperty(accessor,"bundle",{enumerable:true,get(){throw new Error("hostile");}});for(const bad of [new Proxy(valid,{getPrototypeOf(){throw new Error("hostile");}}),accessor,{...valid,extra:true},{spaceId:id(3),keyId:id(20),bundle:terminal()}])await expect(service.issue(bad as never)).rejects.toMatchObject({code:"TRANSACTIONAL_CAPABILITY_JOURNAL_FAILED",message:"Transactional capability journal operation failed."});const output=await service.issue(valid);for(const record of output){expect(Object.isFrozen(record)).toBe(true);expect(Object.isFrozen(record.envelope)).toBe(true);expect(Object.isFrozen(record.idempotency)).toBe(true);expect(record).not.toHaveProperty("plaintext");expect(record).not.toHaveProperty("allow");expect(record).not.toHaveProperty("effectResult");}});
  it("remains private and leaves desktop and package durable gates false",()=>{const source=readFileSync(new URL("./transactional-capability-journal.ts",import.meta.url),"utf8");const conditional=readFileSync(new URL("./transactional-encrypted-work-set.ts",import.meta.url),"utf8");const barrel=readFileSync(new URL("../index.ts",import.meta.url),"utf8");const gate=readFileSync(new URL("../../../../apps/desktop/src/main/durable-spaces-gate.ts",import.meta.url),"utf8");const packageGate=readFileSync(new URL("../../../../apps/desktop/scripts/inspect-storage-capability-package.mjs",import.meta.url),"utf8");expect(`${source}\n${conditional}`).not.toMatch(/node:(?:fs|path|http|https|child_process)|electron|\bipc\b|process\.env|\bfetch\b|broker|effect execution/i);expect(barrel).not.toMatch(/transactional-capability-journal|transactional-encrypted-work-set/);expect(gate).toMatch(/DURABLE_SPACES_ENABLED\s*=\s*false/);expect(packageGate).toMatch(/durableSpacesEnabled:\s*false/);});
});
