import { CanonicalDurableIdSchema } from "@cadrane/contracts";
import { DurableJournalIdempotencySchema, type DurableJournalIdempotency, type DurableJournalRecord } from "@cadrane/contracts/durable-journal";
import { EncryptedWorkStore, type EncryptedWorkStorePutInput, type WorkspaceKeyProvider } from "./encrypted-work-store.js";
import { InMemoryWorkStore } from "./in-memory-work-store.js";
import { enqueueTransactionalPortOperation } from "./transactional-port-queue.js";
import { TransactionalPersistenceError, disposeOpaqueJournalSnapshotForTestOnly, operationBindingSha256ForDurableRecordSetForTestOnly, restoreInMemoryWorkStoreFromSnapshotForTestOnly, snapshotFromInMemoryWorkStoreForTestOnly, validateRecoveredTransactionalStateForTestOnly, type OpaqueJournalSnapshot, type RecoveredTransactionalState, type TransactionReceipt, type TransactionalPersistencePort } from "./transactional-persistence.js";

const MAX = 8 * 1024 * 1024; const KINDS = new Set<EncryptedWorkStorePutInput["entityKind"]>(["space", "source", "source-snapshot", "source-span", "agent", "agent-version", "task", "run", "run-step", "artifact", "review", "revision-request", "permission-request", "permission-decision", "citation", "receipt", "capability-grant", "capability-grant-receipt", "capability-grant-index"]);
const TYPED = Object.getPrototypeOf(Uint8Array.prototype); const LENGTH = Object.getOwnPropertyDescriptor(TYPED, "byteLength")?.get; const BUFFER = Object.getOwnPropertyDescriptor(TYPED, "buffer")?.get; const SHARED = typeof SharedArrayBuffer === "undefined" ? undefined : Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength")?.get;
export interface TransactionalEncryptedWorkSetInput { readonly operationId: string; readonly spaceId: string; readonly keyId: string; readonly writes: readonly { readonly id: string; readonly entityKind: EncryptedWorkStorePutInput["entityKind"]; readonly recordRevision: number; readonly idempotency: DurableJournalIdempotency; readonly kind: "payload" | "blob"; readonly plaintext: Uint8Array; }[]; }
export interface TransactionalEncryptedWorkSetAfterPrerequisiteInput extends TransactionalEncryptedWorkSetInput { readonly prerequisiteOperationId: string; readonly prerequisites: readonly { readonly id: string; readonly entityKind: EncryptedWorkStorePutInput["entityKind"]; readonly recordRevision: number; readonly idempotency: DurableJournalIdempotency; readonly kind: "payload" | "blob"; readonly plaintext: Uint8Array; }[]; }
export class TransactionalEncryptedWorkSetError extends Error { readonly code = "TRANSACTIONAL_ENCRYPTED_WORK_SET_FAILED" as const; constructor() { super("Transactional encrypted work set operation failed."); this.name = "TransactionalEncryptedWorkSetError"; } }

export class TransactionalEncryptedWorkSet {
  private readonly identity: object;
  constructor(private readonly port: TransactionalPersistencePort, private readonly provider: WorkspaceKeyProvider, private readonly refs?: () => string) { try { const identity = port.concurrencyIdentity; if (identity === null || typeof identity !== "object") throw fail(); this.identity = identity; } catch (_e) { throw fail(); } }
  async putAtomic(input: TransactionalEncryptedWorkSetInput): Promise<readonly DurableJournalRecord[]> {
    let owned: Owned | undefined; try { owned = parse(input); } catch (_e) { throw fail(); }
    try { return await enqueueTransactionalPortOperation(this.identity, () => this.run(owned!)); } catch (_e) { throw fail(); } finally { owned?.writes.forEach((item) => item.plaintext.fill(0)); }
  }
  async putAtomicAfterExactPrerequisite(input: TransactionalEncryptedWorkSetAfterPrerequisiteInput): Promise<readonly DurableJournalRecord[]> {
    let owned: OwnedAfter | undefined; try { owned = parseAfter(input); } catch (_e) { throw fail(); }
    try { return await enqueueTransactionalPortOperation(this.identity, () => this.runAfter(owned!)); } catch (_e) { throw fail(); } finally { owned?.writes.forEach((item) => item.plaintext.fill(0)); owned?.prerequisites.forEach((item) => item.plaintext.fill(0)); }
  }
  private async run(owned: Owned): Promise<readonly DurableJournalRecord[]> {
    let recovered: RecoveredTransactionalState | undefined; let candidate: InMemoryWorkStore | undefined; let staged: OpaqueJournalSnapshot | undefined; let verified: RecoveredTransactionalState | undefined; let verifier: InMemoryWorkStore | undefined;
    try {
      recovered = recover(this.port); candidate = restoreInMemoryWorkStoreFromSnapshotForTestOnly(recovered.snapshot);
      const present = owned.writes.map((item) => recovered!.snapshot.journal.records.some((record) => record.id === item.id && record.recordRevision === item.recordRevision));
      if (present.some(Boolean) && !present.every(Boolean)) throw fail();
      if (present.every((value) => !value) && this.port.recoverOperationBinding(owned.operationId) !== undefined) throw fail();
      if (present.every(Boolean)) { const existing = owned.writes.map((item) => recovered!.snapshot.journal.records.find((record) => record.id === item.id && record.recordRevision === item.recordRevision)); if (existing.some((record) => record === undefined)) throw fail(); requireBinding(this.port, owned.operationId, operationBindingSha256ForDurableRecordSetForTestOnly(existing)); }
      const facade = new EncryptedWorkStore(candidate, this.provider, this.refs); const records: DurableJournalRecord[] = [];
      for (const item of owned.writes) records.push(await facade.put({ spaceId: owned.spaceId, keyId: owned.keyId, id: item.id, entityKind: item.entityKind, recordRevision: item.recordRevision, idempotency: item.idempotency, kind: item.kind, plaintext: item.plaintext }));
      const binding = operationBindingSha256ForDurableRecordSetForTestOnly(records);
      if (present.every(Boolean)) { requireBinding(this.port, owned.operationId, binding); return Object.freeze(records.map(ownedRecord)); }
      staged = snapshotFromInMemoryWorkStoreForTestOnly(candidate); const request = Object.freeze({ commitId: owned.operationId, expectedGeneration: recovered.generation, expectedSnapshotSha256: recovered.snapshotSha256, operationBindingSha256: binding, snapshot: staged });
      let receipt: TransactionReceipt; try { receipt = parseReceipt(this.port.commit(request), owned.operationId, recovered.generation + 1); } catch (error) { if (!(error instanceof TransactionalPersistenceError) || error.code !== "INTERRUPTED") throw error; receipt = parseReceipt(this.port.commit(request), owned.operationId, recovered.generation + 1); }
      verified = recover(this.port); if (verified.generation !== receipt.generation || verified.snapshotSha256 !== receipt.snapshotSha256) throw fail(); requireBinding(this.port, owned.operationId, binding);
      verifier = restoreInMemoryWorkStoreFromSnapshotForTestOnly(verified.snapshot); const adopted: DurableJournalRecord[] = [];
      for (const item of owned.writes) adopted.push(await new EncryptedWorkStore(verifier, this.provider, this.refs).put({ spaceId: owned.spaceId, keyId: owned.keyId, id: item.id, entityKind: item.entityKind, recordRevision: item.recordRevision, idempotency: item.idempotency, kind: item.kind, plaintext: item.plaintext }));
      if (operationBindingSha256ForDurableRecordSetForTestOnly(adopted) !== binding) throw fail(); return Object.freeze(adopted.map(ownedRecord));
    } catch (_e) { throw fail(); }
    finally { candidate?.disposeForTestOnly(); verifier?.disposeForTestOnly(); disposeOpaqueJournalSnapshotForTestOnly(recovered?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(staged); disposeOpaqueJournalSnapshotForTestOnly(verified?.snapshot); }
  }
  private async runAfter(owned: OwnedAfter): Promise<readonly DurableJournalRecord[]> {
    let recovered: RecoveredTransactionalState | undefined; let candidate: InMemoryWorkStore | undefined; let staged: OpaqueJournalSnapshot | undefined; let verified: RecoveredTransactionalState | undefined; let verifier: InMemoryWorkStore | undefined;
    try {
      recovered = recover(this.port); candidate = restoreInMemoryWorkStoreFromSnapshotForTestOnly(recovered.snapshot);
      const existingPrerequisites = exactPresent(recovered, owned.prerequisites); requireBinding(this.port, owned.prerequisiteOperationId, operationBindingSha256ForDurableRecordSetForTestOnly(existingPrerequisites));
      const present = owned.writes.map((item) => recovered!.snapshot.journal.records.some((record) => record.id === item.id && record.recordRevision === item.recordRevision));
      if (present.some(Boolean) && !present.every(Boolean)) throw fail();
      if (present.every((value) => !value) && this.port.recoverOperationBinding(owned.operationId) !== undefined) throw fail();
      if (present.every(Boolean)) requireBinding(this.port, owned.operationId, operationBindingSha256ForDurableRecordSetForTestOnly(exactPresent(recovered, owned.writes)));
      const facade = new EncryptedWorkStore(candidate, this.provider, this.refs);
      for (const item of owned.prerequisites) await facade.put(toPut(owned, item));
      const records: DurableJournalRecord[] = []; for (const item of owned.writes) records.push(await facade.put(toPut(owned, item)));
      const binding = operationBindingSha256ForDurableRecordSetForTestOnly(records);
      if (present.every(Boolean)) { requireBinding(this.port, owned.operationId, binding); return Object.freeze(records.map(ownedRecord)); }
      staged = snapshotFromInMemoryWorkStoreForTestOnly(candidate); const request = Object.freeze({ commitId: owned.operationId, expectedGeneration: recovered.generation, expectedSnapshotSha256: recovered.snapshotSha256, operationBindingSha256: binding, snapshot: staged });
      let receipt: TransactionReceipt; try { receipt = parseReceipt(this.port.commit(request), owned.operationId, recovered.generation + 1); } catch (error) { if (!(error instanceof TransactionalPersistenceError) || error.code !== "INTERRUPTED") throw error; receipt = parseReceipt(this.port.commit(request), owned.operationId, recovered.generation + 1); }
      verified = recover(this.port); if (verified.generation !== receipt.generation || verified.snapshotSha256 !== receipt.snapshotSha256) throw fail(); requireBinding(this.port, owned.operationId, binding);
      const verifiedPrerequisites = exactPresent(verified, owned.prerequisites); requireBinding(this.port, owned.prerequisiteOperationId, operationBindingSha256ForDurableRecordSetForTestOnly(verifiedPrerequisites)); verifier = restoreInMemoryWorkStoreFromSnapshotForTestOnly(verified.snapshot); const adopted: DurableJournalRecord[] = []; const adopt = new EncryptedWorkStore(verifier, this.provider, this.refs); for (const item of owned.prerequisites) await adopt.put(toPut(owned, item)); for (const item of owned.writes) adopted.push(await adopt.put(toPut(owned, item))); if (operationBindingSha256ForDurableRecordSetForTestOnly(adopted) !== binding) throw fail(); return Object.freeze(adopted.map(ownedRecord));
    } catch (_e) { throw fail(); }
    finally { candidate?.disposeForTestOnly(); verifier?.disposeForTestOnly(); disposeOpaqueJournalSnapshotForTestOnly(recovered?.snapshot); disposeOpaqueJournalSnapshotForTestOnly(staged); disposeOpaqueJournalSnapshotForTestOnly(verified?.snapshot); }
  }
}
interface Owned { readonly operationId: string; readonly spaceId: string; readonly keyId: string; readonly writes: readonly OwnedWrite[]; }
interface OwnedAfter extends Owned { readonly prerequisiteOperationId: string; readonly prerequisites: readonly OwnedWrite[]; }
interface OwnedWrite { readonly id: string; readonly entityKind: EncryptedWorkStorePutInput["entityKind"]; readonly recordRevision: number; readonly idempotency: DurableJournalIdempotency; readonly kind: "payload" | "blob"; readonly plaintext: Uint8Array; }
function parse(value: unknown): Owned { const raw=ownValues(value,["operationId","spaceId","keyId","writes"]); if(raw===undefined)throw fail();const source=raw.writes;if(!id(raw.operationId)||!id(raw.spaceId)||!id(raw.keyId)||!Array.isArray(source)||Object.getPrototypeOf(source)!==Array.prototype)throw fail();const length=Object.getOwnPropertyDescriptor(source,"length")?.value;if(!Number.isSafeInteger(length)||length<1||length>16||Reflect.ownKeys(source).length!==length+1)throw fail();const decoded:{item:Record<string,unknown>;idem:DurableJournalIdempotency;length:number}[]=[];const pairs=new Set<string>();const revisions=new Map<string,number>();let total=0;const writes:OwnedWrite[]=[];let current:Uint8Array|undefined;try{for(let index=0;index<length;index+=1){const descriptor=Object.getOwnPropertyDescriptor(source,String(index));const item=descriptor===undefined||!("value" in descriptor)?undefined:ownValues(descriptor.value,["id","entityKind","recordRevision","idempotency","kind","plaintext"]);if(item===undefined)throw fail();const idem=DurableJournalIdempotencySchema.safeParse(copyOwnDataObject(item.idempotency));const byteLength=byteLengthOf(item.plaintext);if(!id(item.id)||!KINDS.has(item.entityKind as EncryptedWorkStorePutInput["entityKind"])||!Number.isSafeInteger(item.recordRevision)||(item.recordRevision as number)<1||!idem.success||(item.kind!=="payload"&&item.kind!=="blob"))throw fail();const pair=`${item.id}:${item.recordRevision}`;if(pairs.has(pair)||(revisions.get(item.id as string)??0)>=(item.recordRevision as number))throw fail();pairs.add(pair);revisions.set(item.id as string,item.recordRevision as number);total+=byteLength;if(total>MAX)throw fail();decoded.push({item,idem:idem.data,length:byteLength});}for(const entry of decoded){current=copyBytes(entry.item.plaintext,entry.length);writes.push(Object.freeze({id:entry.item.id as string,entityKind:entry.item.entityKind as EncryptedWorkStorePutInput["entityKind"],recordRevision:entry.item.recordRevision as number,idempotency:entry.idem,kind:entry.item.kind as "payload"|"blob",plaintext:current}));current=undefined;}return Object.freeze({operationId:raw.operationId as string,spaceId:raw.spaceId as string,keyId:raw.keyId as string,writes:Object.freeze(writes)});}catch(_e){current?.fill(0);writes.forEach((item)=>item.plaintext.fill(0));throw fail();} }
function parseAfter(value: unknown): OwnedAfter { const raw=ownValues(value,["operationId","spaceId","keyId","prerequisiteOperationId","prerequisites","writes"]); if(raw===undefined||!id(raw.prerequisiteOperationId)||raw.prerequisiteOperationId===raw.operationId)throw fail(); let prerequisites:OwnedWrite[]=[];let target:Owned|undefined;try{prerequisites=[...parse({operationId:raw.prerequisiteOperationId,spaceId:raw.spaceId,keyId:raw.keyId,writes:raw.prerequisites}).writes];target=parse({operationId:raw.operationId,spaceId:raw.spaceId,keyId:raw.keyId,writes:raw.writes});const total=prerequisites.reduce((sum,item)=>sum+item.plaintext.byteLength,0)+target.writes.reduce((sum,item)=>sum+item.plaintext.byteLength,0);if(total>MAX)throw fail();for(const prior of prerequisites)for(const write of target.writes)if(prior.id===write.id&&prior.recordRevision>=write.recordRevision)throw fail();return Object.freeze({...target,prerequisiteOperationId:raw.prerequisiteOperationId as string,prerequisites:Object.freeze(prerequisites)});}catch(_e){prerequisites.forEach((item)=>item.plaintext.fill(0));target?.writes.forEach((item)=>item.plaintext.fill(0));throw fail();} }
function exactPresent(recovered: RecoveredTransactionalState, writes: readonly OwnedWrite[]): DurableJournalRecord[] { const records=writes.map((item)=>recovered.snapshot.journal.records.find((record)=>record.id===item.id&&record.recordRevision===item.recordRevision)); if(records.some((record)=>record===undefined))throw fail(); return records as DurableJournalRecord[]; }
function toPut(owned: Owned, item: OwnedWrite): EncryptedWorkStorePutInput { return { spaceId:owned.spaceId,keyId:owned.keyId,id:item.id,entityKind:item.entityKind,recordRevision:item.recordRevision,idempotency:item.idempotency,kind:item.kind,plaintext:item.plaintext }; }
function byteLengthOf(value: unknown): number { if (!(value instanceof Uint8Array) || Object.getPrototypeOf(value) !== Uint8Array.prototype || LENGTH === undefined || BUFFER === undefined || Object.hasOwn(value, "byteLength") || Object.hasOwn(value, "buffer") || Object.hasOwn(value, "length")) throw fail(); const length = LENGTH.call(value); const buffer = BUFFER.call(value); if (!Number.isSafeInteger(length) || length < 0 || length > MAX || (SHARED !== undefined && (() => { try { return typeof SHARED.call(buffer) === "number"; } catch (_e) { return false; } })())) throw fail(); return length; }
function copyBytes(value: unknown, length: number): Uint8Array { const copy = new Uint8Array(value as Uint8Array); if (LENGTH?.call(copy) !== length) { copy.fill(0); throw fail(); } return copy; }
function recover(port: TransactionalPersistencePort): RecoveredTransactionalState { let raw: RecoveredTransactionalState | undefined; try { raw = port.recover(); return validateRecoveredTransactionalStateForTestOnly(raw); } catch (_e) { throw fail(); } finally { disposeOpaqueJournalSnapshotForTestOnly(raw?.snapshot); } }
function requireBinding(port: TransactionalPersistencePort, commitId: string, binding: string): void { try { const raw=ownValues(port.recoverOperationBinding(commitId),["commitId","operationBindingSha256"]); if(raw===undefined||raw.commitId!==commitId||typeof raw.operationBindingSha256!=="string"||!/^[a-f0-9]{64}$/.test(raw.operationBindingSha256)||raw.operationBindingSha256!==binding)throw fail(); } catch(_e){throw fail();} }
function parseReceipt(value: unknown, commitId: string, generation: number): TransactionReceipt { const raw=ownValues(value,["commitId","generation","snapshotSha256"]); if(raw===undefined||raw.commitId!==commitId||raw.generation!==generation||typeof raw.snapshotSha256!=="string"||!/^[a-f0-9]{64}$/.test(raw.snapshotSha256))throw fail();return Object.freeze({commitId,generation,snapshotSha256:raw.snapshotSha256}); }
function ownValues(value: unknown, fields: readonly string[]): Record<string,unknown>|undefined { try { if(value===null||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)return undefined;const keys=Reflect.ownKeys(value);if(keys.length!==fields.length)return undefined;const output:Record<string,unknown>={};for(const field of fields){const descriptor=Object.getOwnPropertyDescriptor(value,field);if(descriptor===undefined||!("value" in descriptor))return undefined;output[field]=descriptor.value;}return output;}catch(_e){return undefined;} }
function copyOwnDataObject(value: unknown): Record<string,unknown>|undefined {
  try {
    if(value===null||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)return undefined;
    const keys=Reflect.ownKeys(value);if(keys.length<1||keys.length>3||keys.some((key)=>typeof key!=="string"))return undefined;
    const output:Record<string,unknown>={};
    for(const key of keys){
      if(typeof key!=="string")return undefined;
      const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor===undefined||!("value" in descriptor))return undefined;
      Object.defineProperty(output,key,{value:descriptor.value,enumerable:true,writable:true,configurable:true});
    }
    const kind=Object.getOwnPropertyDescriptor(output,"kind")?.value;
    const expected=kind==="entity"?["kind"]:kind==="task"?["kind","idempotencyKeySha256"]:kind==="run"?["kind","taskId","attempt"]:kind==="revision"?["kind","reviewId","requestSha256"]:kind==="receipt"?["kind","runId"]:undefined;
    if(expected===undefined||keys.length!==expected.length||keys.some((key)=>typeof key!=="string"||!expected.includes(key)))return undefined;
    return output;
  }catch(_e){return undefined;}
}
function id(value: unknown): value is string { return CanonicalDurableIdSchema.safeParse(value).success; } function fail(): TransactionalEncryptedWorkSetError { return new TransactionalEncryptedWorkSetError(); }
function ownedRecord(value: DurableJournalRecord): DurableJournalRecord { return JSON.parse(JSON.stringify(value)) as DurableJournalRecord; }
